import type { Crop, Order, OrderStatus } from "./types";

export const mockCrops: Crop[] = [
  {
    id: "CROP001",
    name: "Organic Tomatoes",
    type: "Vegetable",
    farmer: "Green Valley Farms",
    location: "Fresno, CA",
    quantity: 500,
    price: 2.5,
    harvestDate: new Date("2024-08-15"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Premium",
  },
  {
    id: "CROP002",
    name: "Sweet Corn",
    type: "Vegetable",
    farmer: "Sunshine Acres",
    location: "Ames, IA",
    quantity: 1000,
    price: 0.5,
    harvestDate: new Date("2024-08-20"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Standard",
  },
  {
    id: "CROP003",
    name: "Honeycrisp Apples",
    type: "Fruit",
    farmer: "Orchard Hill",
    location: "Yakima, WA",
    quantity: 800,
    price: 3.0,
    harvestDate: new Date("2024-09-01"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Premium",
  },
  {
    id: "CROP004",
    name: "Hard Red Wheat",
    type: "Grain",
    farmer: "Plains Grain Co.",
    location: "Salina, KS",
    quantity: 10000,
    price: 0.2,
    harvestDate: new Date("2024-07-30"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Standard",
  },
  {
    id: "CROP005",
    name: "Black Beans",
    type: "Legume",
    farmer: "Rio Grande Organics",
    location: "McAllen, TX",
    quantity: 2000,
    price: 1.8,
    harvestDate: new Date("2024-09-10"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Standard",
  },
  {
    id: "CROP006",
    name: "Hass Avocados",
    type: "Fruit",
    farmer: "Green Valley Farms",
    location: "Fresno, CA",
    quantity: 1200,
    price: 1.75,
    harvestDate: new Date("2024-08-25"),
    imageUrl: "https://placehold.co/600x400.png",
    quality: "Premium",
  },
];
