"use client";

import React, {
  createContext,
  useState,
  useContext,
  ReactNode,
  useEffect,
} from "react";

export const translations = {
  English: {
    tagline: "Empowering Farmers, Delivering Freshness",
    quote: "Breathing life into agriculture",
    joinCommunity: "Join Our Community",
    roles: {
      farmer: {
        name: "Farmer",
        description: "Join our network to sell your produce directly.",
      },
      customer: {
        name: "Customer",
        description: "Get fresh, organic products delivered to your doorstep.",
      },
      hub: {
        name: "Hub",
        description: "Manage logistics and connect farmers to customers.",
      },
      restaurant: {
        name: "Restaurant",
        description: "Source fresh ingredients directly from local farms.",
      },
    },
    continue: "Continue",
    ourMission: "Our Mission",
    missionStatement:
      "Manvaasam connects you directly with local farmers through our trusted hub network, ensuring you receive the freshest organic products while supporting sustainable agriculture.",
    footer: "All rights reserved.",
    sidebar: {
      dashboard: "Dashboard",
      profile: "Profile",
      orders: "Orders",
      products: "Products",
      track: "Track Order",
      matchmaking: "Matchmaking",
      voiceAssistant: "Voice Assistant",
      marketing: "Marketing",
      faq: "FAQ",
    },
    signOut: {
      button: "Sign Out",
      title: "Signed Out",
      description: "You have been successfully signed out.",
      errorTitle: "Sign Out Failed",
    },
    auth: {
      welcome: "Welcome to Manvaasam",
      getStarted: "Sign in or create an account to get started.",
      login: "Login",
      register: "Register",
      emailPassword: "Email & Password",
      farmerFaceSignIn: "Farmer Face Sign-In",
      emailLabel: "Email",
      passwordLabel: "Password",
      forgotPassword: "Forgot Password?",
      forgotPasswordTitle: "Forgot Password",
      forgotPasswordDesc: "Enter your email and we'll send a reset link.",
      sendResetLink: "Send Reset Link",
      cancel: "Cancel",
      signIn: "Sign In",
      iamA: "I am a...",
      customer: "Customer",
      farmer: "Farmer",
      faceReg: "Face Registration",
      faceRegDesc: "Center your face in the camera and click capture.",
      capturePhoto: "Capture Photo",
      photoCaptured: "Photo captured successfully!",
      retakePhoto: "Retake Photo",
      usernameLabel: "Username",
      phoneLabel: "Phone Number",
      confirmPasswordLabel: "Confirm Password",
      createAccount: "Create Account",
      hubPortal: "Hub Portal",
      hubDesc: "Manage logistics and connect our network.",
      branchNameLabel: "Branch Name",
      branchIdLabel: "Branch ID",
      hubAdminEmailLabel: "Hub Admin Email",
      registerHub: "Register Hub",
      restaurantPortal: "Restaurant Portal",
      restaurantDesc: "Access your account or register your restaurant.",
      restaurantIdLabel: "Restaurant ID",
      restaurantIdPlaceholder: "Your unique Restaurant ID",
      forgotPasswordRestaurantDesc:
        "Enter your Restaurant ID or email to receive a password reset link.",
      restaurantIdOrEmailLabel: "Restaurant ID or Email",
      restaurantIdOrEmailPlaceholder: "ID or email",
      restaurantNameLabel: "Restaurant Name",
      restaurantEmailLabel: "Restaurant Email",
      restaurantPhoneLabel: "Restaurant Phone",
      locationLabel: "Location",
      registerRestaurant: "Register Restaurant",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome back",
      loading: "Loading...",
      totalRevenue: "Total Revenue",
      fromLastMonth: "from last month",
      newCustomers: "New Customers",
      productsSold: "Products Sold",
      yourProfile: "Your Profile",
      viewProfile: "View your profile",
    },
    profile: {
      title: "My Profile",
      description: "View and manage your account details.",
      cardTitle: "User Information",
      cardDescription: "Your personal and account details.",
      editProfile: "Edit Profile",
      editDialogTitle: "Edit Profile",
      editDialogDescription:
        "Make changes to your profile here. Click save when you're done.",
      profilePicture: "Profile Picture",
      branchName: "Branch Name",
      username: "Username",
      email: "Email",
      phone: "Phone Number",
      saveChanges: "Save Changes",
      cancel: "Cancel",
      updateSuccessTitle: "Success",
      updateSuccessDescription: "Your profile has been updated successfully.",
      updateErrorTitle: "Update Failed",
      loadError: "Could not load user profile.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      branchIdLabel: "Branch ID",
      userTypeLabel: "User Type",
      memberSinceLabel: "Member Since",
      noProfileData: "No profile data found.",
    },
    orders: {
      title: "Orders",
      description: "Here's a list of all the recent orders.",
      cardTitle: "All Orders",
      cardDescription:
        "Review and manage all customer orders. Click on an order to view details.",
      searchPlaceholder: "Search by order ID or customer name...",
      orderId: "Order ID",
      customer: "Customer",
      status: "Status",
      date: "Date",
      total: "Total",
      actions: "Actions",
      trackLive: "Track Live",
      dialogTitle: "Order Tracking",
      dialogDescription: "Live shipping and delivery updates for your order.",
      currentLocation: "Current Location",
      reachedState: "Reached Your State",
      estimatedDelivery: "Estimated Delivery",
      shipmentHistory: "Shipment History",
      noDetails: "No shipping details available for this order yet.",
    },
    products: {
      title: "Products",
      description:
        "Browse and purchase fresh produce directly from our farmers.",
      freshCarrots: "Fresh Carrots",
      kgPrice: "1kg - Rs.20",
      addToCart: "Add to Cart",
      buyNow: "Buy Now",
      dialogTitle: "Place Your Order",
      dialogDescription:
        "Please fill in your details to complete the purchase.",
      nameLabel: "Name",
      namePlaceholder: "Your full name",
      emailLabel: "Email ID",
      emailPlaceholder: "you@example.com",
      mobileLabel: "Mobile Number",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "WhatsApp Number",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "Address",
      addressPlaceholder: "123 Main St, City",
      countryLabel: "Country",
      countryPlaceholder: "e.g. India",
      stateLabel: "State",
      statePlaceholder: "e.g. Maharashtra",
      districtLabel: "District",
      districtPlaceholder: "e.g. Pune",
      cancel: "Cancel",
      placeOrder: "Place Order",
      orderSuccessTitle: "Order Placed!",
      orderSuccessDescription: "Your order has been successfully submitted.",
      orderFailTitle: "Order Failed",
      orderFailDescription: "Something went wrong.",
    },
    matchmaking: {
      title: "Farmer Matchmaking",
      description:
        "Connect directly with farmers to source the freshest ingredients.",
      specializesIn: "Specializes in:",
      sendInquiry: "Send Inquiry",
      dialogTitle: "Contact",
      dialogDescription:
        "Send a message directly to inquire about their produce.",
      subjectLabel: "Subject",
      subjectPlaceholder: "e.g., Inquiry about fresh tomatoes",
      messageLabel: "Message",
      messagePlaceholder: "Hi {farmerName}, I'm interested in...",
      cancel: "Cancel",
      send: "Send Inquiry",
      inquirySuccessTitle: "Inquiry Sent!",
      inquirySuccessDescription:
        "Your message has been successfully sent to {farmerName}.",
    },
    faq: {
      title: "Frequently Asked Questions",
      description: "Here are some answers to common questions.",
      cardTitle: "Common Questions",
      cardDescription:
        "Find answers to the most frequently asked questions below.",
    },
    marketing: {
      title: "Marketing",
      description: "Tools and analytics for your marketing campaigns.",
      comingSoon: "Coming Soon",
      comingSoonDescription:
        "This section is under construction. Check back later for exciting new marketing tools!",
      workingHard:
        "We are working hard to bring you features like campaign tracking, analytics, and promotional tools.",
    },
  },
  Tamil: {
    tagline: "விவசாயிகளை மேம்படுத்துதல், புத்துணர்ச்சியை வழங்குதல்",
    quote: "உணவுத்துறை வேவசாயிக்கு உயிருத்துவோம்",
    joinCommunity: "எங்கள் சமூகத்தில் சேரவும்",
    roles: {
      farmer: {
        name: "விவசாயி",
        description:
          "உங்கள் விளைபொருட்களை நேரடியாக விற்க எங்கள் நெட்வொர்க்கில் சேரவும்.",
      },
      customer: {
        name: "வாடிக்கையாளர்",
        description:
          "புதிய, ஆர்கானிக் பொருட்களை உங்கள் வீட்டு வாசலில் பெறுங்கள்.",
      },
      hub: {
        name: "மையம்",
        description:
          "விநியோகத்தை நிர்வகித்து விவசாயிகளை வாடிக்கையாளர்களுடன் இணைக்கவும்.",
      },
      restaurant: {
        name: "உணவகம்",
        description:
          "உள்ளூர் பண்ணைகளிலிருந்து நேரடியாக புதிய பொருட்களைப் பெறுங்கள்.",
      },
    },
    continue: "தொடரவும்",
    ourMission: "எங்கள் நோக்கம்",
    missionStatement:
      "மன்வாசம் உங்களை உள்ளூர் விவசாயிகளுடன் எங்கள் நம்பகமான மைய நெட்வொர்க் மூலம் நேரடியாக இணைக்கிறது, நிலையான விவசாயத்தை ஆதரிக்கும் அதே வேளையில் புத்துணர்ச்சியான ஆர்கானிக் தயாரிப்புகளைப் பெறுவதை உறுதி செய்கிறது.",
    footer: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    sidebar: {
      dashboard: "முகப்பு",
      profile: "சுயவிவரம்",
      orders: "ஆர்டர்கள்",
      products: "பொருட்கள்",
      track: "ஆர்டரைக் கண்காணிக்கவும்",
      matchmaking: "பொருத்தம்",
      voiceAssistant: "குரல் உதவியாளர்",
      marketing: "சந்தைப்படுத்தல்",
      faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    },
    signOut: {
      button: "வெளியேறு",
      title: "வெளியேறப்பட்டது",
      description: "நீங்கள் வெற்றிகரமாக வெளியேறிவிட்டீர்கள்.",
      errorTitle: "வெளியேற முடியவில்லை",
    },
    auth: {
      welcome: "மன்வாசமிற்கு வரவேற்கிறோம்",
      getStarted: "தொடங்குவதற்கு உள்நுழையவும் அல்லது ஒரு கணக்கை உருவாக்கவும்.",
      login: "உள்நுழை",
      register: "பதிவு செய்க",
      emailPassword: "மின்னஞ்சல் & கடவுச்சொல்",
      farmerFaceSignIn: "விவசாயி முக உள்நுழைவு",
      emailLabel: "மின்னஞ்சல்",
      passwordLabel: "கடவுச்சொல்",
      forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
      forgotPasswordTitle: "கடவுச்சொல்லை மறந்துவிட்டீர்களா",
      forgotPasswordDesc:
        "உங்கள் மின்னஞ்சலை உள்ளிடவும், நாங்கள் ஒரு மீட்டமைப்பு இணைப்பை அனுப்புவோம்.",
      sendResetLink: "மீட்டமைப்பு இணைப்பை அனுப்பு",
      cancel: "ரத்துசெய்",
      signIn: "உள்நுழைக",
      iamA: "நான் ஒரு...",
      customer: "வாடிக்கையாளர்",
      farmer: "விவசாயி",
      faceReg: "முக பதிவு",
      faceRegDesc:
        "உங்கள் முகத்தை கேமராவில் மையப்படுத்தி, பிடி என்பதைக் கிளிக் செய்யவும்.",
      capturePhoto: "புகைப்படம் எடு",
      photoCaptured: "புகைப்படம் வெற்றிகரமாக எடுக்கப்பட்டது!",
      retakePhoto: "மீண்டும் புகைப்படம் எடு",
      usernameLabel: "பயனர்பெயர்",
      phoneLabel: "தொலைபேசி எண்",
      confirmPasswordLabel: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
      createAccount: "கணக்கை உருவாக்கு",
      hubPortal: "மையம் போர்டల్",
      hubDesc:
        "தளவாடங்களை நிர்வகிக்கவும் மற்றும் எங்கள் நெட்வொர்க்கை இணைக்கவும்.",
      branchNameLabel: "கிளை பெயர்",
      branchIdLabel: "கிளை ஐடி",
      hubAdminEmailLabel: "மைய நிர்வாகி மின்னஞ்சல்",
      registerHub: "மையத்தை பதிவு செய்யுங்கள்",
      restaurantPortal: "உணவக போர்டల్",
      restaurantDesc:
        "உங்கள் கணக்கை அணுகவும் அல்லது உங்கள் உணவகத்தை பதிவு செய்யவும்.",
      restaurantIdLabel: "உணவக ஐடி",
      restaurantIdPlaceholder: "உங்கள் தனிப்பட்ட உணவக ஐடி",
      forgotPasswordRestaurantDesc:
        "கடவுச்சொல் மீட்டமைப்பு இணைப்பைப் பெற உங்கள் உணவக ஐடி அல்லது மின்னஞ்சலை உள்ளிடவும்.",
      restaurantIdOrEmailLabel: "உணவக ஐடி அல்லது மின்னஞ்சல்",
      restaurantIdOrEmailPlaceholder: "ஐடி அல்லது மின்னஞ்சல்",
      restaurantNameLabel: "உணவகத்தின் பெயர்",
      restaurantEmailLabel: "உணவக மின்னஞ்சல்",
      restaurantPhoneLabel: "உணவக தொலைபேசி",
      locationLabel: "இடம்",
      registerRestaurant: "உணவகத்தை பதிவு செய்யுங்கள்",
    },
    dashboard: {
      title: "முகப்பு",
      welcome: "மீண்டும் வருக",
      loading: "ஏற்றுகிறது...",
      totalRevenue: "மொத்த வருவாய்",
      fromLastMonth: "கடந்த மாதத்திலிருந்து",
      newCustomers: "புதிய வாடிக்கையாளர்கள்",
      productsSold: "விற்பனை செய்யப்பட்ட பொருட்கள்",
      yourProfile: "உங்கள் சுயவிவரம்",
      viewProfile: "உங்கள் சுயவிவரத்தைக் காண்க",
    },
    profile: {
      title: "என் சுயவிவரம்",
      description: "உங்கள் கணக்கு விவரங்களைக் கண்டு நிர்வகிக்கவும்.",
      cardTitle: "பயனர் தகவல்",
      cardDescription: "உங்கள் தனிப்பட்ட மற்றும் கணக்கு விவரங்கள்.",
      editProfile: "சுயவிவரத்தைத் திருத்து",
      editDialogTitle: "சுயவிவரத்தைத் திருத்து",
      editDialogDescription:
        "உங்கள் சுயவிவரத்தில் மாற்றங்களை இங்கே செய்யுங்கள். முடிந்ததும் சேமி என்பதைக் கிளிக் செய்யவும்.",
      profilePicture: "சுயவிவரப் படம்",
      branchName: "கிளை பெயர்",
      username: "பயனர்பெயர்",
      email: "மின்னஞ்சல்",
      phone: "தொலைபேசி எண்",
      saveChanges: "மாற்றங்களைச் சேமிக்கவும்",
      cancel: "ரத்துசெய்",
      updateSuccessTitle: "வெற்றி",
      updateSuccessDescription:
        "உங்கள் சுயவிவரம் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது.",
      updateErrorTitle: "புதுப்பிப்பு தோல்வியடைந்தது",
      loadError: "பயனர் சுயவிவரத்தை ஏற்ற முடியவில்லை.",
      emailLabel: "மின்னஞ்சல்",
      phoneLabel: "தொலைபேசி",
      branchIdLabel: "கிளை ஐடி",
      userTypeLabel: "பயனர் வகை",
      memberSinceLabel: "உறுப்பினர்",
      noProfileData: "சுயவிவரத் தரவு எதுவும் கிடைக்கவில்லை.",
    },
    orders: {
      title: "ஆர்டர்கள்",
      description: "சமீபத்திய ஆர்டர்களின் பட்டியல் இங்கே.",
      cardTitle: "அனைத்து ஆர்டர்களும்",
      cardDescription:
        "வாடிக்கையாளர் ஆர்டர்களை மதிப்பாய்வு செய்து நிர்வகிக்கவும். விவரங்களைக் காண ஒரு ஆர்டரைக் கிளிக் செய்யவும்.",
      searchPlaceholder:
        "ஆர்டர் ஐடி அல்லது வாடிக்கையாளர் பெயர் மூலம் தேடவும்...",
      orderId: "ஆர்டர் ஐடி",
      customer: "வாடிக்கையாளர்",
      status: "நிலை",
      date: "தேதி",
      total: "மொத்தம்",
      actions: "செயல்கள்",
      trackLive: "நேரலையில் கண்காணிக்கவும்",
      dialogTitle: "ஆர்டர் கண்காணிப்பு",
      dialogDescription:
        "உங்கள் ஆர்டருக்கான நேரடி ஷிப்பிங் மற்றும் டெலிவரி புதுப்பிப்புகள்.",
      currentLocation: "தற்போதைய இடம்",
      reachedState: "உங்கள் மாநிலத்தை அடைந்தது",
      estimatedDelivery: "மதிப்பிடப்பட்ட டெலிவரி",
      shipmentHistory: "ஏற்றுமதி வரலாறு",
      noDetails:
        "இந்த ஆர்டருக்கு இன்னும் ஷிப்பிங் விவரங்கள் எதுவும் கிடைக்கவில்லை.",
    },
    products: {
      title: "பொருட்கள்",
      description:
        "எங்கள் விவசாயிகளிடமிருந்து நேரடியாக புதிய விளைபொருட்களை உலவவும் மற்றும் வாங்கவும்.",
      freshCarrots: "புதிய கேரட்",
      kgPrice: "1கிலோ - ரூ.20",
      addToCart: "வண்டியில் சேர்",
      buyNow: "இப்போது வாங்கு",
      dialogTitle: "உங்கள் ஆர்டரை வைக்கவும்",
      dialogDescription: "கொள்முதலை முடிக்க உங்கள் விவரங்களை நிரப்பவும்.",
      nameLabel: "பெயர்",
      namePlaceholder: "உங்கள் முழுப்பெயர்",
      emailLabel: "மின்னஞ்சல் முகவரி",
      emailPlaceholder: "you@example.com",
      mobileLabel: "கைபேசி எண்",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "வாட்ஸ்அப் எண்",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "முகவரி",
      addressPlaceholder: "123 மெயின் தெரு, நகரம்",
      countryLabel: "நாடு",
      countryPlaceholder: "எ.கா. இந்தியா",
      stateLabel: "மாநிலம்",
      statePlaceholder: "எ.கா. மகாராஷ்டிரா",
      districtLabel: "மாவட்டம்",
      districtPlaceholder: "எ.கா. புனே",
      cancel: "ரத்துசெய்",
      placeOrder: "ஆர்டர் செய்",
      orderSuccessTitle: "ஆர்டர் செய்யப்பட்டது!",
      orderSuccessDescription: "உங்கள் ஆர்டர் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.",
      orderFailTitle: "ஆர்டர் தோல்வி",
      orderFailDescription: "ஏதோ தவறு நடந்துவிட்டது.",
    },
    matchmaking: {
      title: "விவசாயி பொருத்தம்",
      description: "புதிய பொருட்களைப் பெற விவசாயிகளுடன் நேரடியாக இணையுங்கள்.",
      specializesIn: "இதில் நிபுணத்துவம் பெற்றது:",
      sendInquiry: "விசாரணை அனுப்பு",
      dialogTitle: "தொடர்பு கொள்ள",
      dialogDescription:
        "அவர்களின் விளைப்பொருட்கள் பற்றி விசாரிக்க সরাসরি একটি செய்தியை அனுப்பவும்.",
      subjectLabel: "பொருள்",
      subjectPlaceholder: "எ.கா., புதிய தக்காளி பற்றிய விசாரணை",
      messageLabel: "செய்தி",
      messagePlaceholder: "வணக்கம் {farmerName}, நான் இதில் ஆர்வமாக உள்ளேன்...",
      cancel: "ரத்துசெய்",
      send: "விசாரணை அனுப்பு",
      inquirySuccessTitle: "விசாரணை அனுப்பப்பட்டது!",
      inquirySuccessDescription:
        "உங்கள் செய்தி {farmerName}க்கு வெற்றிகரமாக அனுப்பப்பட்டது.",
    },
    faq: {
      title: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      description: "பொதுவான கேள்விகளுக்கான சில பதில்கள் இங்கே.",
      cardTitle: "பொதுவான கேள்விகள்",
      cardDescription:
        "கீழே அடிக்கடி கேட்கப்படும் கேள்விகளுக்கான பதில்களைக் கண்டறியவும்.",
    },
    marketing: {
      title: "சந்தைப்படுத்தல்",
      description:
        "உங்கள் சந்தைப்படுத்தல் பிரச்சாரங்களுக்கான கருவிகள் மற்றும் பகுப்பாய்வுகள்.",
      comingSoon: "விரைவில்",
      comingSoonDescription:
        "இந்த பகுதி கட்டுமானத்தில் உள்ளது. அற்புதமான புதிய சந்தைப்படுத்தல் கருவிகளுக்காக பின்னர் மீண்டும் பார்க்கவும்!",
      workingHard:
        " பிரச்சார கண்காணிப்பு, பகுப்பாய்வு மற்றும் விளம்பர கருவிகள் போன்ற அம்சங்களை உங்களுக்கு வழங்க நாங்கள் கடுமையாக உழைத்து வருகிறோம்.",
    },
  },
  Malayalam: {
    tagline: "കർഷകരെ ശാക്തീകരിക്കുന്നു, പുതുമ നൽകുന്നു",
    quote: "കൃഷിക്ക് ജീവൻ നൽകുന്നു",
    joinCommunity: "ഞങ്ങളുടെ കമ്മ്യൂണിറ്റിയിൽ ചേരുക",
    roles: {
      farmer: {
        name: "കർഷകൻ",
        description:
          "നിങ്ങളുടെ ഉൽപ്പന്നങ്ങൾ നേരിട്ട് വിൽക്കാൻ ഞങ്ങളുടെ നെറ്റ്‌വർക്കിൽ ചേരുക.",
      },
      customer: {
        name: "ഉപഭോക്താവ്",
        description:
          "പുതിയ, ഓർഗാനിക് ഉൽപ്പന്നങ്ങൾ നിങ്ങളുടെ വീട്ടുവാതിൽക്കൽ എത്തിക്കുക.",
      },
      hub: {
        name: "ഹബ്",
        description:
          "ലോജിസ്റ്റിക്സ് നിയന്ത്രിക്കുക, കർഷകരെ ഉപഭോക്താക്കളുമായി ബന്ധിപ്പിക്കുക.",
      },
      restaurant: {
        name: "റെസ്റ്റോറന്റ്",
        description: "പ്രാദേശിക ഫാമുകളിൽ നിന്ന് നേരിട്ട് പുതിയ ചേരുവകൾ നേടുക.",
      },
    },
    continue: "തുടരുക",
    ourMission: "ഞങ്ങളുടെ ദൗത്യം",
    missionStatement:
      "സുസ്ഥിരമായ കൃഷിയെ പിന്തുണച്ചുകൊണ്ട് നിങ്ങൾക്ക് ഏറ്റവും പുതിയ ഓർഗാനിക് ഉൽപ്പന്നങ്ങൾ ലഭിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കിക്കൊണ്ട് ഞങ്ങളുടെ വിശ്വസ്ത ഹബ് നെറ്റ്‌വർക്ക് വഴി മൻവാസം നിങ്ങളെ പ്രാദേശിക കർഷകരുമായി നേരിട്ട് ബന്ധിപ്പിക്കുന്നു.",
    footer: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
    sidebar: {
      dashboard: "ഡാഷ്ബോർഡ്",
      profile: "പ്രൊഫൈൽ",
      orders: "ഓർഡറുകൾ",
      products: "ഉൽപ്പന്നങ്ങൾ",
      track: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
      matchmaking: "മാച്ച് മേക്കിംഗ്",
      voiceAssistant: "വോയിസ് അസിസ്റ്റന്റ്",
      marketing: "മാർക്കറ്റിംഗ്",
      faq: "പതിവുചോദ്യങ്ങൾ",
    },
    signOut: {
      button: "സൈൻ ഔട്ട് ചെയ്യുക",
      title: "സൈൻ ഔട്ട് ചെയ്തു",
      description: "നിങ്ങൾ വിജയകരമായി സൈൻ ഔട്ട് ചെയ്തു.",
      errorTitle: "സൈൻ ഔട്ട് പരാജയപ്പെട്ടു",
    },
    auth: {
      welcome: "മൻവാസത്തിലേക്ക് സ്വാഗതം",
      getStarted:
        "ആരംഭിക്കാൻ സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ ഒരു അക്കൗണ്ട് ഉണ്ടാക്കുക.",
      login: "പ്രവേശിക്കുക",
      register: "രജിസ്റ്റർ ചെയ്യുക",
      emailPassword: "ഇമെയിൽ & പാസ്‌വേഡ്",
      farmerFaceSignIn: "കർഷക മുഖം സൈൻ-ഇൻ",
      emailLabel: "ഇമെയിൽ",
      passwordLabel: "പാസ്വേഡ്",
      forgotPassword: "പാസ്വേഡ് മറന്നോ?",
      forgotPasswordTitle: "പാസ്വേഡ് മറന്നോ",
      forgotPasswordDesc:
        "നിങ്ങളുടെ ഇമെയിൽ നൽകുക, ഞങ്ങൾ ഒരു പുനഃസജ്ജീകരണ ലിങ്ക് അയയ്ക്കും.",
      sendResetLink: "പുനഃസജ്ജീകരണ ലിങ്ക് അയയ്ക്കുക",
      cancel: "റദ്ദാക്കുക",
      signIn: "സൈൻ ഇൻ ചെയ്യുക",
      iamA: "ഞാൻ ഒരു...",
      customer: "ഉപഭോക്താവ്",
      farmer: "കർഷകൻ",
      faceReg: "മുഖം രജിസ്ട്രേഷൻ",
      faceRegDesc:
        "നിങ്ങളുടെ മുഖം ക്യാമറയിൽ കേന്ദ്രീകരിച്ച് ക്യാപ്ചർ ക്ലിക്കുചെയ്യുക.",
      capturePhoto: "ഫോട്ടോ എടുക്കുക",
      photoCaptured: "ഫോട്ടോ വിജയകരമായി എടുത്തു!",
      retakePhoto: "വീണ്ടും ഫോട്ടോ എടുക്കുക",
      usernameLabel: "ഉപയോക്തൃനാമം",
      phoneLabel: "ഫോൺ നമ്പർ",
      confirmPasswordLabel: "പാസ്വേഡ് സ്ഥിരീകരിക്കുക",
      createAccount: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
      hubPortal: "ഹബ് പോർട്ടൽ",
      hubDesc:
        "ലോജിസ്റ്റിക്സ് നിയന്ത്രിക്കുകയും ഞങ്ങളുടെ നെറ്റ്‌വർക്കിനെ ബന്ധിപ്പിക്കുകയും ചെയ്യുക.",
      branchNameLabel: "ബ്രാഞ്ചിന്റെ പേര്",
      branchIdLabel: "ബ്രാഞ്ച് ഐഡി",
      hubAdminEmailLabel: "ഹബ് അഡ്മിൻ ഇമെയിൽ",
      registerHub: "ഹബ് രജിസ്റ്റർ ചെയ്യുക",
      restaurantPortal: "റെസ്റ്റോറന്റ് പോർട്ടൽ",
      restaurantDesc:
        "നിങ്ങളുടെ അക്കൗണ്ട് ആക്‌സസ് ചെയ്യുക അല്ലെങ്കിൽ നിങ്ങളുടെ റെസ്റ്റോറന്റ് രജിസ്റ്റർ ചെയ്യുക.",
      restaurantIdLabel: "റെസ്റ്റോറന്റ് ഐഡി",
      restaurantIdPlaceholder: "നിങ്ങളുടെ തനതായ റെസ്റ്റോറന്റ് ഐഡി",
      forgotPasswordRestaurantDesc:
        "പാസ്‌വേഡ് പുനഃസജ്ജീകരണ ലിങ്ക് ലഭിക്കുന്നതിന് നിങ്ങളുടെ റെസ്റ്റോറന്റ് ഐഡിയോ ഇമെയിലോ നൽകുക.",
      restaurantIdOrEmailLabel: "റെസ്റ്റോറന്റ് ഐഡി അല്ലെങ്കിൽ ഇമെയിൽ",
      restaurantIdOrEmailPlaceholder: "ഐഡി അല്ലെങ്കിൽ ഇമെയിൽ",
      restaurantNameLabel: "റെസ്റ്റോറന്റിന്റെ പേര്",
      restaurantEmailLabel: "റെസ്റ്റോറന്റ് ഇമെയിൽ",
      restaurantPhoneLabel: "റെസ്റ്റോറന്റ് ഫോൺ",
      locationLabel: "സ്ഥലം",
      registerRestaurant: "റെസ്റ്റോറന്റ് രജിസ്റ്റർ ചെയ്യുക",
    },
    dashboard: {
      title: "ഡാഷ്ബോർഡ്",
      welcome: "വീണ്ടും സ്വാഗതം",
      loading: "ലോഡ് ചെയ്യുന്നു...",
      totalRevenue: "മൊത്ത വരുമാനം",
      fromLastMonth: "കഴിഞ്ഞ മാസത്തേക്കാൾ",
      newCustomers: "പുതിയ ഉപഭോക്താക്കൾ",
      productsSold: "വിറ്റ ഉൽപ്പന്നങ്ങൾ",
      yourProfile: "നിങ്ങളുടെ പ്രൊഫൈൽ",
      viewProfile: "നിങ്ങളുടെ പ്രൊഫൈൽ കാണുക",
    },
    profile: {
      title: "എന്റെ പ്രൊഫൈൽ",
      description: "നിങ്ങളുടെ അക്കൗണ്ട് വിവരങ്ങൾ കാണുക, നിയന്ത്രിക്കുക.",
      cardTitle: "ഉപയോക്തൃ വിവരങ്ങൾ",
      cardDescription: "നിങ്ങളുടെ വ്യക്തിഗത, അക്കൗണ്ട് വിവരങ്ങൾ.",
      editProfile: "പ്രൊഫൈൽ എഡിറ്റുചെയ്യുക",
      editDialogTitle: "പ്രൊഫൈൽ എഡിറ്റുചെയ്യുക",
      editDialogDescription:
        "നിങ്ങളുടെ പ്രൊഫൈലിൽ മാറ്റങ്ങൾ ഇവിടെ വരുത്തുക. പൂർത്തിയാകുമ്പോൾ സേവ് ക്ലിക്കുചെയ്യുക.",
      profilePicture: "പ്രൊഫൈൽ ചിത്രം",
      branchName: "ബ്രാഞ്ചിന്റെ പേര്",
      username: "ഉപയോക്തൃനാമം",
      email: "ഇമെയിൽ",
      phone: "ഫോൺ നമ്പർ",
      saveChanges: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
      cancel: "റദ്ദാക്കുക",
      updateSuccessTitle: "വിജയം",
      updateSuccessDescription:
        "നിങ്ങളുടെ പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റುചെയ്‌തു.",
      updateErrorTitle: "അപ്ഡേറ്റ് പരാജയപ്പെട്ടു",
      loadError: "ഉപയോക്തൃ പ്രൊഫൈൽ ലോഡുചെയ്യാൻ കഴിഞ്ഞില്ല.",
      emailLabel: "ഇമെയിൽ",
      phoneLabel: "ഫോൺ",
      branchIdLabel: "ബ്രാഞ്ച് ഐഡി",
      userTypeLabel: "ഉപയോക്തൃ തരം",
      memberSinceLabel: "അംഗമായത് മുതൽ",
      noProfileData: "പ്രൊഫൈൽ ഡാറ്റ ലഭ്യമല്ല.",
    },
    orders: {
      title: "ഓർഡറുകൾ",
      description: "സമീപകാല ഓർഡറുകളുടെ ഒരു ലിസ്റ്റ് ഇതാ.",
      cardTitle: "എല്ലാ ഓർഡറുകളും",
      cardDescription:
        "ഉപഭോക്തൃ ഓർഡറുകൾ അവലോകനം ചെയ്യുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക. വിശദാംശങ്ങൾ കാണുന്നതിന് ഒരു ഓർഡറിൽ ക്ലിക്കുചെയ്യുക.",
      searchPlaceholder:
        "ഓർഡർ ഐഡി അല്ലെങ്കിൽ ഉപഭോക്തൃ നാമം ഉപയോഗിച്ച് തിരയുക...",
      orderId: "ഓർഡർ ഐഡി",
      customer: "ഉപഭോക്താവ്",
      status: "നില",
      date: "തീയതി",
      total: "ആകെ",
      actions: "പ്രവർത്തനങ്ങൾ",
      trackLive: "ലൈവ് ട്രാക്ക് ചെയ്യുക",
      dialogTitle: "ഓർഡർ ട്രാക്കിംഗ്",
      dialogDescription:
        "നിങ്ങളുടെ ഓർഡറിനായുള്ള ലൈവ് ഷിപ്പിംഗ്, ഡെലിവറി അപ്‌ഡേറ്റുകൾ.",
      currentLocation: "നിലവിലെ സ്ഥലം",
      reachedState: "നിങ്ങളുടെ സംസ്ഥാനത്ത് എത്തി",
      estimatedDelivery: "കണക്കാക്കിയ ഡെലിവറി",
      shipmentHistory: "ഷിപ്പ്മെന്റ് ചരിത്രം",
      noDetails: "ഈ ഓർഡറിന് ഷിപ്പിംഗ് വിശദാംശങ്ങൾ ലഭ്യമല്ല.",
    },
    products: {
      title: "ഉൽപ്പന്നങ്ങൾ",
      description:
        "ഞങ്ങളുടെ കർഷകരിൽ നിന്ന് നേരിട്ട് പുതിയ ഉൽപ്പന്നങ്ങൾ ബ്രൗസ് ചെയ്യുകയും വാങ്ങുകയും ചെയ്യുക.",
      freshCarrots: "ഫ്രഷ് കാരറ്റ്",
      kgPrice: "1 കിലോ - 20 രൂപ",
      addToCart: "കാർട്ടിലേക്ക് ചേർക്കുക",
      buyNow: "ഇപ്പോൾ വാങ്ങുക",
      dialogTitle: "നിങ്ങളുടെ ഓർഡർ നൽകുക",
      dialogDescription:
        "വാങ്ങൽ പൂർത്തിയാക്കാൻ നിങ്ങളുടെ വിശദാംശങ്ങൾ പൂരിപ്പിക്കുക.",
      nameLabel: "പേര്",
      namePlaceholder: "നിങ്ങളുടെ പൂർണ്ണമായ പേര്",
      emailLabel: "ഇമെയിൽ ഐഡി",
      emailPlaceholder: "you@example.com",
      mobileLabel: "മൊബൈൽ നമ്പർ",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "വാട്ട്‌സ്ആപ്പ് നമ്പർ",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "വിലാസം",
      addressPlaceholder: "123 മെയിൻ സ്ട്രീറ്റ്, നഗരം",
      countryLabel: "രാജ്യം",
      countryPlaceholder: "ഉദാ. ഇന്ത്യ",
      stateLabel: "സംസ്ഥാനം",
      statePlaceholder: "ഉദാ. മഹാരാഷ്ട്ര",
      districtLabel: "ജില്ല",
      districtPlaceholder: "ഉദാ. പൂനെ",
      cancel: "റദ്ദാക്കുക",
      placeOrder: "ഓർഡർ നൽകുക",
      orderSuccessTitle: "ഓർഡർ നൽകി!",
      orderSuccessDescription: "നിങ്ങളുടെ ഓർഡർ വിജയകരമായി സമർപ്പിച്ചു.",
      orderFailTitle: "ഓർഡർ പരാജയപ്പെട്ടു",
      orderFailDescription: "എന്തോ കുഴപ്പം സംഭവിച്ചു.",
    },
    matchmaking: {
      title: "കർഷക മാച്ച് മേക്കിംഗ്",
      description: "പുതിയ ചേരുവകൾക്കായി കർഷകരുമായി നേരിട്ട് ബന്ധപ്പെടുക.",
      specializesIn: "പ്രത്യേകത:",
      sendInquiry: "അന്വേഷണം അയയ്ക്കുക",
      dialogTitle: "ബന്ധപ്പെടുക",
      dialogDescription:
        "അവരുടെ ഉൽപ്പന്നങ്ങളെക്കുറിച്ച് അന്വേഷിക്കാൻ നേരിട്ട് ഒരു സന്ദേശം അയയ്ക്കുക.",
      subjectLabel: "വിഷയം",
      subjectPlaceholder: "ഉദാഹരണത്തിന്, പുതിയ തക്കാളിയെക്കുറിച്ചുള്ള അന്വേഷണം",
      messageLabel: "സന്ദേശം",
      messagePlaceholder: "ഹായ് {farmerName}, എനിക്ക് താൽപ്പര്യമുണ്ട്...",
      cancel: "റദ്ദാക്കുക",
      send: "അന്വേഷണം അയയ്ക്കുക",
      inquirySuccessTitle: "അന്വേഷണം അയച്ചു!",
      inquirySuccessDescription:
        "നിങ്ങളുടെ സന്ദേശം {farmerName} എന്നയാൾക്ക് വിജയകരമായി അയച്ചു.",
    },
    faq: {
      title: "പതിവുചോദ്യങ്ങൾ",
      description: "സാധാരണ ചോദ്യങ്ങൾക്കുള്ള ചില ഉത്തരങ്ങൾ ഇതാ.",
      cardTitle: "സാധാരണ ചോദ്യങ്ങൾ",
      cardDescription:
        "ഏറ്റവും കൂടുതൽ ചോദിക്കുന്ന ചോദ്യങ്ങൾക്കുള്ള ഉത്തരങ്ങൾ താഴെ കണ്ടെത്തുക.",
    },
    marketing: {
      title: "മാർക്കറ്റിംഗ്",
      description:
        "നിങ്ങളുടെ മാർക്കറ്റിംഗ് കാമ്പെയ്‌നുകൾക്കായുള്ള ഉപകരണങ്ങളും അനലിറ്റിക്‌സും.",
      comingSoon: "ഉടൻ വരുന്നു",
      comingSoonDescription:
        "ഈ വിഭാഗം നിർമ്മാണത്തിലാണ്. ആവേശകരമായ പുതിയ മാർക്കറ്റിംഗ് ഉപകരണങ്ങൾക്കായി പിന്നീട് വീണ്ടും പരിശോധിക്കുക!",
      workingHard:
        "കാമ്പെയ്ൻ ട്രാക്കിംഗ്, അനലിറ്റിക്സ്, പ്രൊമോഷണൽ ടൂളുകൾ പോലുള്ള സവിശേഷതകൾ നിങ്ങൾക്ക് നൽകാൻ ഞങ്ങൾ കഠിനമായി പരിശ്രമിക്കുന്നു.",
    },
  },
  Telugu: {
    tagline: "రైతులకు సాధికారత, తాజాదనాన్ని అందించడం",
    quote: "వ్యవసాయానికి ప్రాణం పోస్తున్నాము",
    joinCommunity: "మా సంఘంలో చేరండి",
    roles: {
      farmer: {
        name: "రైతు",
        description:
          "మీ ఉత్పత్తులను నేరుగా విక్రయించడానికి మా నెట్వర్క్‌లో చేరండి.",
      },
      customer: {
        name: "వినియోగదారుడు",
        description: "తాజా, సేంద్రీయ ఉత్పత్తులను మీ ఇంటి వద్ద పొందండి.",
      },
      hub: {
        name: "హబ్",
        description:
          "లాజిస్టిక్స్ నిర్వహించండి మరియు రైతులను వినియోగదారులతో కనెక్ట్ చేయండి.",
      },
      restaurant: {
        name: "రెస్టారెంట్",
        description: "స్థానిక పొలాల నుండి నేరుగా తాజా పదార్థాలను పొందండి.",
      },
    },
    continue: "కొనసాగించు",
    ourMission: "మా లక్ష్యం",
    missionStatement:
      "సుస్థిర వ్యవసాయానికి మద్దతు ఇస్తూ, తాజా సేంద్రీయ ఉత్పత్తులను మీరు పొందేలా మా విశ్వసనీయ హబ్ నెట్‌వర్క్ ద్వారా మన్వాసం మిమ్మల్ని స్థానిక రైతులతో నేరుగా కలుపుతుంది.",
    footer: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
    sidebar: {
      dashboard: "డాష్బోర్డ్",
      profile: "ప్రొఫైల్",
      orders: "ఆదేశాలు",
      products: "ఉత్పత్తులు",
      track: "ఆర్డర్ ట్రాక్ చేయండి",
      matchmaking: "మ్యాచ్ మేకింగ్",
      voiceAssistant: "వాయిస్ అసిస్టెంట్",
      marketing: "మార్కెటింగ్",
      faq: "ఎఫ్ ఎ క్యూ",
    },
    signOut: {
      button: "సైన్ అవుట్ చేయండి",
      title: "సైన్ అవుట్ చేయబడింది",
      description: "మీరు విజయవంతంగా సైన్ అవుట్ చేసారు.",
      errorTitle: "సైన్ అవుట్ విఫలమైంది",
    },
    auth: {
      welcome: "మన్వాసంకు స్వాగతం",
      getStarted: "ప్రారంభించడానికి సైన్ ఇన్ చేయండి లేదా ఖాతాను సృష్టించండి.",
      login: "లాగిన్",
      register: "నమోదు చేసుకోండి",
      emailPassword: "ఇమెయిల్ & పాస్వర్డ్",
      farmerFaceSignIn: "రైతు ఫేస్ సైన్-ఇన్",
      emailLabel: "ఇమెయిల్",
      passwordLabel: "పాస్వర్డ్",
      forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
      forgotPasswordTitle: "పాస్వర్డ్ మర్చిపోయారా",
      forgotPasswordDesc:
        "మీ ఇమెయిల్‌ను నమోదు చేయండి మరియు మేము రీసెట్ లింక్‌ను పంపుతాము.",
      sendResetLink: "రీసెట్ లింక్‌ను పంపండి",
      cancel: "రద్దు చేయండి",
      signIn: "సైన్ ఇన్ చేయండి",
      iamA: "నేను ఒక...",
      customer: "వినియోగదారుడు",
      farmer: "రైతు",
      faceReg: "ఫేస్ రిజిస్ట్రేషన్",
      faceRegDesc:
        "మీ ముఖాన్ని కెమెరాలో కేంద్రీకరించండి మరియు క్యాప్చర్ క్లిక్ చేయండి.",
      capturePhoto: "ఫోటోను క్యాప్చర్ చేయండి",
      photoCaptured: "ఫోటో విజయవంతంగా క్యాప్చర్ చేయబడింది!",
      retakePhoto: "ఫోటోను మళ్లీ తీసుకోండి",
      usernameLabel: "యూజర్పేరు",
      phoneLabel: "ఫోను నంబరు",
      confirmPasswordLabel: "పాస్వర్డ్ను నిర్ధారించండి",
      createAccount: "ఖాతాను సృష్టించండి",
      hubPortal: "హబ్ పోర్టల్",
      hubDesc:
        "లాజిస్టిక్స్ నిర్వహించండి మరియు మా నెట్‌వర్క్‌ను కనెక్ట్ చేయండి.",
      branchNameLabel: "శాఖ పేరు",
      branchIdLabel: "శాఖ ఐడి",
      hubAdminEmailLabel: "హబ్ అడ్మిన్ ఇమెయిల్",
      registerHub: "హబ్‌ను నమోదు చేయండి",
      restaurantPortal: "రెస్టారెంట్ పోర్టల్",
      restaurantDesc:
        "మీ ఖాతాను యాక్సెస్ చేయండి లేదా మీ రెస్టారెంట్‌ను నమోదు చేయండి.",
      restaurantIdLabel: "రెస్టారెంట్ ఐడి",
      restaurantIdPlaceholder: "మీ ప్రత్యేక రెస్టారెంట్ ఐడి",
      forgotPasswordRestaurantDesc:
        "పాస్‌వర్డ్ రీసెట్ లింక్‌ను స్వీకరించడానికి మీ రెస్టారెంట్ ఐడి లేదా ఇమెయిల్‌ను నమోదు చేయండి.",
      restaurantIdOrEmailLabel: "రెస్టారెంట్ ఐడి లేదా ఇమెయిల్",
      restaurantIdOrEmailPlaceholder: "ఐడి లేదా ఇమెయిల్",
      restaurantNameLabel: "రెస్టారెంట్ పేరు",
      restaurantEmailLabel: "రెస్టారెంట్ ఇమెయిల్",
      restaurantPhoneLabel: "రెస్టారెంట్ ఫోన్",
      locationLabel: "స్థానం",
      registerRestaurant: "రెస్టారెంట్‌ను నమోదు చేయండి",
    },
    dashboard: {
      title: "డాష్బోర్డ్",
      welcome: "మళ్ళీ స్వాగతం",
      loading: "లోడ్ అవుతోంది...",
      totalRevenue: "మొత్తం ఆదాయం",
      fromLastMonth: "గత నెల నుండి",
      newCustomers: "కొత్త వినియోగదారులు",
      productsSold: "అమ్మిన ఉత్పత్తులు",
      yourProfile: "మీ ప్రొఫైల్",
      viewProfile: "మీ ప్రొఫైల్ ను చూడండి",
    },
    profile: {
      title: "నా ప్రొఫైల్",
      description: "మీ ఖాతా వివరాలను వీక్షించండి మరియు నిర్వహించండి.",
      cardTitle: "వినియోగదారు సమాచారం",
      cardDescription: "మీ వ్యక్తిగత మరియు ఖాతా వివరాలు.",
      editProfile: "ప్రొఫైల్ ను మార్చు",
      editDialogTitle: "ప్రొఫైల్ ను మార్చు",
      editDialogDescription:
        "మీ ప్రొఫైల్ లో మార్పులు ఇక్కడ చేయండి. పూర్తయిన తర్వాత సేవ్ క్లిక్ చేయండి.",
      profilePicture: "ప్రొఫైల్ చిత్రం",
      branchName: "శాఖ పేరు",
      username: "యూజర్పేరు",
      email: "ఇమెయిల్",
      phone: "ఫోను నంబరు",
      saveChanges: "మార్పులను భద్రపరచు",
      cancel: "రద్దు చేయండి",
      updateSuccessTitle: "విజయం",
      updateSuccessDescription: "మీ ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది.",
      updateErrorTitle: "నవీకరణ విఫలమైంది",
      loadError: "వినియోగదారు ప్రొఫైల్ ను లోడ్ చేయలేకపోయింది.",
      emailLabel: "ఇమెయిల్",
      phoneLabel: "ఫోన్",
      branchIdLabel: "శాఖ ఐడి",
      userTypeLabel: "వినియోగదారు రకం",
      memberSinceLabel: "సభ్యుడు",
      noProfileData: "ప్రొఫైల్ డేటా కనుగొనబడలేదు.",
    },
    orders: {
      title: "ఆర్డర్లు",
      description: "ఇటీవలి ఆర్డర్ల జాబితా ఇక్కడ ఉంది.",
      cardTitle: "అన్ని ఆర్డర్లు",
      cardDescription:
        "వినియోగదారుల ఆర్డర్లను సమీక్షించండి మరియు నిర్వహించండి. వివరాలను వీక్షించడానికి ఆర్డర్‌పై క్లిక్ చేయండి.",
      searchPlaceholder: "ఆర్డర్ ఐడి లేదా వినియోగదారు పేరు ద్వారా శోధించండి...",
      orderId: "ఆర్డర్ ఐడి",
      customer: "వినియోగదారు",
      status: "స్థితి",
      date: "తేదీ",
      total: "మొత్తం",
      actions: "చర్యలు",
      trackLive: "ప్రత్యక్షంగా ట్రాక్ చేయండి",
      dialogTitle: "ఆర్డర్ ట్రాకింగ్",
      dialogDescription:
        "మీ ఆర్డర్ కోసం ప్రత్యక్ష షిప్పింగ్ మరియు డెలివరీ నవీకరణలు.",
      currentLocation: "ప్రస్తుత స్థానం",
      reachedState: "మీ రాష్ట్రానికి చేరుకుంది",
      estimatedDelivery: "అంచనా వేసిన డెలివరీ",
      shipmentHistory: "షిప్‌మెంట్ చరిత్ర",
      noDetails: "ఈ ఆర్డర్‌కు ఇంకా షిప్పింగ్ వివరాలు అందుబాటులో లేవు.",
    },
    products: {
      title: "ఉత్పత్తులు",
      description:
        "మా రైతుల నుండి నేరుగా తాజా ఉత్పత్తులను బ్రౌజ్ చేయండి మరియు కొనుగోలు చేయండి.",
      freshCarrots: "తాజా క్యారెట్లు",
      kgPrice: "1కిలో - రూ.20",
      addToCart: "కార్ట్‌కు జోడించండి",
      buyNow: "ఇప్పుడే కొనండి",
      dialogTitle: "మీ ఆర్డర్ ఉంచండి",
      dialogDescription:
        "కొనుగోలు పూర్తి చేయడానికి దయచేసి మీ వివరాలను పూరించండి.",
      nameLabel: "పేరు",
      namePlaceholder: "మీ పూర్తి పేరు",
      emailLabel: "ఇమెయిల్ ఐడి",
      emailPlaceholder: "you@example.com",
      mobileLabel: "మొబైల్ నంబర్",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "వాట్సాప్ నంబర్",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "చిరునామా",
      addressPlaceholder: "123 మెయిన్ స్ట్రీట్, నగరం",
      countryLabel: "దేశం",
      countryPlaceholder: "ఉదా. భారతదేశం",
      stateLabel: "రాష్ట్రం",
      statePlaceholder: "ఉదా. మహారాష్ట్ర",
      districtLabel: "జిల్లా",
      districtPlaceholder: "ఉదా. పూణే",
      cancel: "రద్దు చేయండి",
      placeOrder: "ఆర్డర్ ఉంచండి",
      orderSuccessTitle: "ఆర్డర్ ఉంచబడింది!",
      orderSuccessDescription: "మీ ఆర్డర్ విజయవంతంగా సమర్పించబడింది.",
      orderFailTitle: "ఆర్డర్ విఫలమైంది",
      orderFailDescription: "ఏదో పొరపాటు జరిగింది.",
    },
    matchmaking: {
      title: "రైతు మ్యాచ్ మేకింగ్",
      description:
        "తాజా పదార్థాలను సోర్స్ చేయడానికి రైతులతో నేరుగా కనెక్ట్ అవ్వండి.",
      specializesIn: "ప్రత్యేకత:",
      sendInquiry: "విచారణ పంపండి",
      dialogTitle: "సంప్రదించండి",
      dialogDescription:
        "వారి ఉత్పత్తుల గురించి విచారించడానికి నేరుగా సందేశం పంపండి.",
      subjectLabel: "విషయం",
      subjectPlaceholder: "ఉదా., తాజా టమోటాల గురించి విచారణ",
      messageLabel: "సందేశం",
      messagePlaceholder: "హాయ్ {farmerName}, నాకు ఆసక్తి ఉంది...",
      cancel: "రద్దు చేయండి",
      send: "విచారణ పంపండి",
      inquirySuccessTitle: "విచారణ పంపబడింది!",
      inquirySuccessDescription:
        "మీ సందేశం {farmerName}కు విజయవంతంగా పంపబడింది.",
    },
    faq: {
      title: "తరచుగా అడిగే ప్రశ్నలు",
      description: "సాధారణ ప్రశ్నలకు కొన్ని సమాధానాలు ఇక్కడ ఉన్నాయి.",
      cardTitle: "సాధారణ ప్రశ్నలు",
      cardDescription: "క్రింద తరచుగా అడిగే ప్రశ్నలకు సమాధానాలు కనుగొనండి.",
    },
    marketing: {
      title: "మార్కెటింగ్",
      description: "మీ మార్కెటింగ్ ప్రచారాల కోసం సాధనాలు మరియు విశ్లేషణలు.",
      comingSoon: "త్వరలో వస్తుంది",
      comingSoonDescription:
        "ఈ విభాగం నిర్మాణంలో ఉంది. ఉత్తేజకరమైన కొత్త మార్కెటింగ్ సాధనాల కోసం తర్వాత తిరిగి తనిఖీ చేయండి!",
      workingHard:
        "ప్రచార ట్రాకింగ్, విశ్లేషణలు మరియు ప్రచార సాధనాలు వంటి లక్షణాలను మీకు అందించడానికి మేము తీవ్రంగా కృషి చేస్తున్నాము.",
    },
  },
  Hindi: {
    tagline: "किसानों को सशक्त बनाना, ताजगी पहुंचाना",
    quote: "कृषि में जीवन फूंक रहे हैं",

    joinCommunity: "हमारे समुदाय में शामिल हों",
    roles: {
      farmer: {
        name: "किसान",
        description: "अपनी उपज सीधे बेचने के लिए हमारे नेटवर्क से जुड़ें।",
      },
      customer: {
        name: "ग्राहक",
        description: "ताजा, जैविक उत्पाद अपने दरवाजे पर प्राप्त करें।",
      },
      hub: {
        name: "हब",
        description:
          "लॉजिस्टिक्स प्रबंधित करें और किसानों को ग्राहकों से जोड़ें।",
      },
      restaurant: {
        name: "रेस्टोरेंट",
        description: "स्थानीय खेतों से सीधे ताजा सामग्री प्राप्त करें।",
      },
    },
    continue: "जारी रखें",
    ourMission: "हमारा विशेष कार्य",
    missionStatement:
      "मनवाசம் आपको हमारे विश्वसनीय हब नेटवर्क के माध्यम से सीधे स्थानीय किसानों से जोड़ता है, यह सुनिश्चित करता है कि आपको स्थायी कृषि का समर्थन करते हुए सबसे ताज़ा जैविक उत्पाद प्राप्त हों।",
    footer: "सर्वाधिकार सुरक्षित।",
    sidebar: {
      dashboard: "डैशबोर्ड",
      profile: "प्रोफ़ाइल",
      orders: "आदेश",
      products: "उत्पादों",
      track: "ऑर्डर ट्रैक करें",
      matchmaking: "मैचमेकिंग",
      voiceAssistant: "आवाज सहायक",
      marketing: "विपणन",
      faq: "सामान्य प्रश्न",
    },
    signOut: {
      button: "साइन आउट",
      title: "साइन आउट किया गया",
      description: "आप सफलतापूर्वक साइन आउट हो गए हैं।",
      errorTitle: "साइन आउट विफल",
    },
    auth: {
      welcome: "मनवाசம் में आपका स्वागत है",
      getStarted: "शुरू करने के लिए साइन इन करें या एक खाता बनाएँ।",
      login: "लॉग इन करें",
      register: "पंजीकरण करवाना",
      emailPassword: "ईमेल और पासवर्ड",
      farmerFaceSignIn: "किसान फेस साइन-इन",
      emailLabel: "ईमेल",
      passwordLabel: "पासवर्ड",
      forgotPassword: "पासवर्ड भूल गए?",
      forgotPasswordTitle: "पासवर्ड भूल गए",
      forgotPasswordDesc: "अपना ईमेल दर्ज करें और हम एक रीसेट लिंक भेजेंगे।",
      sendResetLink: "रीसेट लिंक भेजें",
      cancel: "रद्द करें",
      signIn: "साइन इन करें",
      iamA: "मैं एक...",
      customer: "ग्राहक",
      farmer: "किसान",
      faceReg: "फेस पंजीकरण",
      faceRegDesc:
        "अपने चेहरे को कैमरे में केंद्रित करें और कैप्चर पर क्लिक करें।",
      capturePhoto: "फोटो कैप्चर करें",
      photoCaptured: "फोटो सफलतापूर्वक कैप्चर किया गया!",
      retakePhoto: "फोटो फिर से लें",
      usernameLabel: "उपयोगकर्ता नाम",
      phoneLabel: "फोन नंबर",
      confirmPasswordLabel: "पासवर्ड की पुष्टि कीजिये",
      createAccount: "खाता बनाएं",
      hubPortal: "हब पोर्टल",
      hubDesc: "लॉजिस्टिक्स प्रबंधित करें और हमारे नेटवर्क को कनेक्ट करें।",
      branchNameLabel: "शाखा का नाम",
      branchIdLabel: "शाखा आईडी",
      hubAdminEmailLabel: "हब व्यवस्थापक ईमेल",
      registerHub: "हब पंजीकृत करें",
      restaurantPortal: "रेस्तरां पोर्टल",
      restaurantDesc: "अपने खाते तक पहुंचें या अपने रेस्तरां को पंजीकृत करें।",
      restaurantIdLabel: "रेस्तरां आईडी",
      restaurantIdPlaceholder: "आपकी अनूठी रेस्तरां आईडी",
      forgotPasswordRestaurantDesc:
        "पासवर्ड रीसेट लिंक प्राप्त करने के लिए अपनी रेस्तरां आईडी या ईमेल दर्ज करें।",
      restaurantIdOrEmailLabel: "रेस्तरां आईडी या ईमेल",
      restaurantIdOrEmailPlaceholder: "आईडी या ईमेल",
      restaurantNameLabel: "रेस्तरां का नाम",
      restaurantEmailLabel: "रेस्तरां ईमेल",
      restaurantPhoneLabel: "रेस्तरां फोन",
      locationLabel: "स्थान",
      registerRestaurant: "रेस्तरां पंजीकृत करें",
    },
    dashboard: {
      title: "डैशबोर्ड",
      welcome: "वापसी पर स्वागत है",
      loading: "लोड हो रहा है...",
      totalRevenue: "कुल राजस्व",
      fromLastMonth: "पिछले महीने से",
      newCustomers: "नए ग्राहक",
      productsSold: "बेचे गए उत्पाद",
      yourProfile: "आपकी प्रोफ़ाइल",
      viewProfile: "अपनी प्रोफ़ाइल देखें",
    },
    profile: {
      title: "मेरी प्रोफ़ाइल",
      description: "अपने खाते का विवरण देखें और प्रबंधित करें।",
      cardTitle: "उपयोगकर्ता जानकारी",
      cardDescription: "आपका व्यक्तिगत और खाता विवरण।",
      editProfile: "प्रोफ़ाइल संपादित करें",
      editDialogTitle: "प्रोफ़ाइल संपादित करें",
      editDialogDescription:
        "अपनी प्रोफ़ाइल में परिवर्तन यहाँ करें। जब आप पूरा कर लें तो सहेजें पर क्लिक करें।",
      profilePicture: "प्रोफ़ाइल तस्वीर",
      branchName: "शाखा का नाम",
      username: "उपयोगकर्ता नाम",
      email: "ईमेल",
      phone: "फोन नंबर",
      saveChanges: "परिवर्तनों को सहेजें",
      cancel: "रद्द करें",
      updateSuccessTitle: "सफलता",
      updateSuccessDescription: "आपकी प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई है।",
      updateErrorTitle: "अपडेट विफल",
      loadError: "उपयोगकर्ता प्रोफ़ाइल लोड नहीं हो सका।",
      emailLabel: "ईमेल",
      phoneLabel: "फोन",
      branchIdLabel: "शाखा आईडी",
      userTypeLabel: "उपयोगकर्ता प्रकार",
      memberSinceLabel: "सदस्य",
      noProfileData: "कोई प्रोफ़ाइल डेटा नहीं मिला।",
    },
    orders: {
      title: "आदेश",
      description: "यहाँ हाल के सभी आदेशों की एक सूची है।",
      cardTitle: "सभी आदेश",
      cardDescription:
        "सभी ग्राहक आदेशों की समीक्षा और प्रबंधन करें। विवरण देखने के लिए एक आदेश पर क्लिक करें।",
      searchPlaceholder: "आदेश आईडी या ग्राहक नाम से खोजें...",
      orderId: "आदेश आईडी",
      customer: "ग्राहक",
      status: "स्थिति",
      date: "तारीख",
      total: "कुल",
      actions: "कार्रवाई",
      trackLive: "लाइव ट्रैक करें",
      dialogTitle: "आदेश ट्रैकिंग",
      dialogDescription: "आपके आदेश के लिए लाइव शिपिंग और डिलीवरी अपडेट।",
      currentLocation: "वर्तमान स्थान",
      reachedState: "आपके राज्य में पहुँच गया",
      estimatedDelivery: "अनुमानित डिलीवरी",
      shipmentHistory: "शिपमेंट इतिहास",
      noDetails: "इस आदेश के लिए अभी तक कोई शिपिंग विवरण उपलब्ध नहीं है।",
    },
    products: {
      title: "उत्पाद",
      description: "हमारे किसानों से सीधे ताजा उपज ब्राउज़ करें और खरीदें।",
      freshCarrots: "ताजा गाजर",
      kgPrice: "1 किलो - 20 रुपये",
      addToCart: "कार्ट में डालें",
      buyNow: "अभी खरीदें",
      dialogTitle: "अपना आदेश दें",
      dialogDescription: "खरीद पूरी करने के लिए कृपया अपना विवरण भरें।",
      nameLabel: "नाम",
      namePlaceholder: "आपका पूरा नाम",
      emailLabel: "ईमेल आईडी",
      emailPlaceholder: "you@example.com",
      mobileLabel: "मोबाइल नंबर",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "व्हाट्सएप नंबर",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "पता",
      addressPlaceholder: "123 मेन स्ट्रीट, शहर",
      countryLabel: "देश",
      countryPlaceholder: "जैसे भारत",
      stateLabel: "राज्य",
      statePlaceholder: "जैसे महाराष्ट्र",
      districtLabel: "जिला",
      districtPlaceholder: "जैसे पुणे",
      cancel: "रद्द करें",
      placeOrder: "आदेश दें",
      orderSuccessTitle: "आदेश दिया गया!",
      orderSuccessDescription: "आपका आदेश सफलतापूर्वक प्रस्तुत किया गया है।",
      orderFailTitle: "आदेश विफल",
      orderFailDescription: "कुछ गलत हो गया।",
    },
    matchmaking: {
      title: "किसान मैचमेकिंग",
      description: "ताजा सामग्री के लिए सीधे किसानों से जुड़ें।",
      specializesIn: "में माहिर:",
      sendInquiry: "पूछताछ भेजें",
      dialogTitle: "संपर्क करें",
      dialogDescription:
        "उनकी उपज के बारे में पूछताछ करने के लिए सीधे एक संदेश भेजें।",
      subjectLabel: "विषय",
      subjectPlaceholder: "जैसे, ताजा टमाटर के बारे में पूछताछ",
      messageLabel: "संदेश",
      messagePlaceholder: "नमस्ते {farmerName}, मुझे इसमें दिलचस्पी है...",
      cancel: "रद्द करें",
      send: "पूछताछ भेजें",
      inquirySuccessTitle: "पूछताछ भेजी गई!",
      inquirySuccessDescription:
        "आपका संदेश {farmerName} को सफलतापूर्वक भेज दिया गया है।",
    },
    faq: {
      title: "अक्सर पूछे जाने वाले प्रश्न",
      description: "यहाँ आम सवालों के कुछ जवाब दिए गए हैं।",
      cardTitle: "आम सवाल",
      cardDescription: "नीचे अक्सर पूछे जाने वाले सवालों के जवाब पाएं।",
    },
    marketing: {
      title: "विपणन",
      description: "आपके विपणन अभियानों के लिए उपकरण और विश्लेषण।",
      comingSoon: "जल्द आ रहा है",
      comingSoonDescription:
        "यह अनुभाग निर्माणाधीन है। रोमांचक नए विपणन उपकरणों के लिए बाद में वापस देखें!",
      workingHard:
        "हम आपको अभियान ट्रैकिंग, विश्लेषण और प्रचार उपकरण जैसी सुविधाएँ लाने के लिए कड़ी मेहनत कर रहे हैं।",
    },
  },
  Kannada: {
    tagline: "ರೈತರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು, ತಾಜಾತನವನ್ನು ತಲುಪಿಸುವುದು",
    quote: "ಕೃಷಿಗೆ ಜೀವ ನೀಡುತ್ತಿದ್ದೇವೆ",

    joinCommunity: "ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ",
    roles: {
      farmer: {
        name: "ರೈತ",
        description:
          "ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳನ್ನು ನೇರವಾಗಿ ಮಾರಾಟ ಮಾಡಲು ನಮ್ಮ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ.",
      },
      customer: {
        name: "ಗ್ರಾಹಕ",
        description:
          "ತಾಜಾ, ಸಾವಯವ ಉತ್ಪನ್ನಗಳನ್ನು ನಿಮ್ಮ ಮನೆ ಬಾಗಿಲಿಗೆ ತಲುಪಿಸಲಾಗುತ್ತದೆ.",
      },
      hub: {
        name: "ಕೇಂದ್ರ",
        description:
          "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಅನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ರೈತರನ್ನು ಗ್ರಾಹಕರಿಗೆ ಸಂಪರ್ಕಿಸಿ.",
      },
      restaurant: {
        name: "ರೆಸ್ಟೋರೆಂಟ್",
        description: "ಸ್ಥಳೀಯ ಜಮೀನುಗಳಿಂದ ನೇರವಾಗಿ ತಾಜಾ ಪದಾರ್ಥಗಳನ್ನು ಪಡೆಯಿರಿ.",
      },
    },
    continue: "ಮುಂದುವರಿಸಿ",
    ourMission: "ನಮ್ಮ ಧ್ಯೇಯ",
    missionStatement:
      "ಮನ್ವಾസം ನಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಕೇಂದ್ರ ನೆಟ್‌ವರ್ಕ್ ಮೂಲಕ ನಿಮ್ಮನ್ನು ಸ್ಥಳೀಯ ರೈತರೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ, ಸುಸ್ಥಿರ ಕೃಷಿಯನ್ನು ಬೆಂಬಲಿಸುವಾಗ ನೀವು ತಾಜಾ ಸಾವಯವ ಉತ್ಪನ್ನಗಳನ್ನು ಪಡೆಯುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
    footer: "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    sidebar: {
      dashboard: "ಡ್ಯಾಶ್ಬೋರ್ಡ್",
      profile: "ಪ್ರೊಫೈಲ್",
      orders: "ಆದೇಶಗಳು",
      products: "ಉತ್ಪನ್ನಗಳು",
      track: "ಆದೇಶವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
      matchmaking: "ಮ್ಯಾಚ್ ಮೇಕಿಂಗ್",
      voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ",
      marketing: "ಮಾರ್ಕೆಟಿಂಗ್",
      faq: "ఎఫ్ఎక్యూ",
    },
    signOut: {
      button: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
      title: "ಸೈನ್ ಔಟ್ ಮಾಡಲಾಗಿದೆ",
      description: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಿದ್ದೀರಿ.",
      errorTitle: "ಸೈನ್ ಔಟ್ ವಿಫಲವಾಗಿದೆ",
    },
    auth: {
      welcome: "ಮನ್ವಾസംಗೆ ಸ್ವಾಗತ",
      getStarted: "ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ಖಾತೆಯನ್ನು ರಚಿಸಿ.",
      login: "ಲಾಗಿನ್ ಮಾಡಿ",
      register: "ನೋಂದಣಿ ಮಾಡಿ",
      emailPassword: "ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್ವರ್డ్",
      farmerFaceSignIn: "ರೈತ ಮುಖ ಸೈನ್-ಇన్",
      emailLabel: "ಇಮೇಲ್",
      passwordLabel: "ಪಾಸ್ವರ್డ్",
      forgotPassword: "ಪಾಸ್ವರ್డ్ ಮರೆತಿರಾ?",
      forgotPasswordTitle: "ಪಾಸ್ವರ್డ్ ಮರೆತಿರಾ",
      forgotPasswordDesc:
        "ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ನಾವು ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಅನ್ನು ಕಳುಹಿಸುತ್ತೇವೆ.",
      sendResetLink: "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
      cancel: "ರದ್ದುಮಾಡಿ",
      signIn: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
      iamA: "ನಾನು ಒಬ್ಬ...",
      customer: "ಗ್ರಾಹಕ",
      farmer: "ರೈತ",
      faceReg: "ಮುಖ ನೋಂದಣಿ",
      faceRegDesc:
        "ನಿಮ್ಮ ಮುಖವನ್ನು ಕ್ಯಾಮರಾದಲ್ಲಿ ಕೇಂದ್ರೀಕರಿಸಿ ಮತ್ತು ಕ್ಯಾಪ್ಚರ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
      capturePhoto: "ಫೋಟೋ ಸೆರೆಹಿಡಿಯಿರಿ",
      photoCaptured: "ಫೋಟೋ ಯಶಸ್ವಿಯಾಗಿ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ!",
      retakePhoto: "ಫೋಟೋವನ್ನು ಮರುಪಡೆಯಿರಿ",
      usernameLabel: "ಬಳಕೆದಾರಹೆಸರು",
      phoneLabel: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
      confirmPasswordLabel: "ಪಾಸ್ವರ್డ్ ದೃಢೀಕರಿಸಿ",
      createAccount: "ಖಾತೆ ತೆರೆ",
      hubPortal: "ಹಬ್ ಪೋರ್ಟಲ್",
      hubDesc:
        "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಅನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ನಮ್ಮ ನೆಟ್ವರ್ಕ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.",
      branchNameLabel: "ಶಾಖೆಯ ಹೆಸರು",
      branchIdLabel: "ಶಾಖೆ ಐಡಿ",
      hubAdminEmailLabel: "ಹಬ್ ನಿರ್ವಾಹಕ ಇಮೇಲ್",
      registerHub: "ಹಬ್ ನೋಂದಾಯಿಸಿ",
      restaurantPortal: "ರೆಸ್ಟೋರೆಂಟ್ ಪೋರ್ಟಲ್",
      restaurantDesc:
        "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಿ ಅಥವಾ ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಅನ್ನು ನೋಂದಾಯಿಸಿ.",
      restaurantIdLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ",
      restaurantIdPlaceholder: "ನಿಮ್ಮ ಅನನ್ಯ ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ",
      forgotPasswordRestaurantDesc:
        "ಪಾಸ್ವರ್డ్ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಅನ್ನು ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ ಅಥವಾ ಇಮೇಲ್ ಅನ್ನು ನಮೂದಿಸಿ.",
      restaurantIdOrEmailLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ ಅಥವಾ ಇಮೇಲ್",
      restaurantIdOrEmailPlaceholder: "ಐಡಿ ಅಥವಾ ಇಮೇಲ್",
      restaurantNameLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಹೆಸರು",
      restaurantEmailLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಇಮೇಲ್",
      restaurantPhoneLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಫೋನ್",
      locationLabel: "ಸ್ಥಳ",
      registerRestaurant: "ರೆಸ್ಟೋರೆಂಟ್ ನೋಂದಾಯಿಸಿ",
    },
    dashboard: {
      title: "ಡ್ಯಾಶ್ಬೋರ್ಡ್",
      welcome: "ಮತ್ತೆ ಸ್ವಾಗತ",
      loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      totalRevenue: "ಒಟ್ಟು ಆದಾಯ",
      fromLastMonth: "ಕಳೆದ ತಿಂಗಳಿನಿಂದ",
      newCustomers: "ಹೊಸ ಗ್ರಾಹಕರು",
      productsSold: "ಮಾರಾಟವಾದ ಉತ್ಪನ್ನಗಳು",
      yourProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್",
      viewProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    },
    profile: {
      title: "ನನ್ನ ಪ್ರೊಫೈಲ್",
      description: "ನಿಮ್ಮ ಖಾತೆಯ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.",
      cardTitle: "ಬಳಕೆದಾರ ಮಾಹಿತಿ",
      cardDescription: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮತ್ತು ಖಾತೆ ವಿವರಗಳು.",
      editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
      editDialogTitle: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
      editDialogDescription:
        "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‍ನಲ್ಲಿ ಇಲ್ಲಿ ಬದಲಾವಣೆಗಳನ್ನು ಮಾಡಿ. ನೀವು ಮುಗಿದ ನಂತರ ಉಳಿಸು ಕ್ಲಿಕ್ ಮಾಡಿ.",
      profilePicture: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ",
      branchName: "ಶಾಖೆಯ ಹೆಸರು",
      username: "ಬಳಕೆದಾರಹೆಸರು",
      email: "ಇಮೇಲ್",
      phone: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
      saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
      cancel: "ರದ್ದುಮಾಡಿ",
      updateSuccessTitle: "ಯಶಸ್ಸು",
      updateSuccessDescription: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
      updateErrorTitle: "ನವೀಕರಣ ವಿಫలವಾಗಿದೆ",
      loadError: "ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
      emailLabel: "ಇಮೇಲ್",
      phoneLabel: "ದೂರವಾಣಿ",
      branchIdLabel: "ಶಾಖೆ ಐಡಿ",
      userTypeLabel: "ಬಳಕೆದಾರ ಪ್ರಕಾರ",
      memberSinceLabel: "ಸದಸ್ಯ",
      noProfileData: "ಯಾವುದೇ ಪ್ರೊಫೈಲ್ ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ.",
    },
    orders: {
      title: "ಆದೇಶಗಳು",
      description: "ಇತ್ತೀಚಿನ ಎಲ್ಲಾ ಆದೇಶಗಳ ಪಟ್ಟಿ ಇಲ್ಲಿದೆ.",
      cardTitle: "ಎಲ್ಲಾ ಆದೇಶಗಳು",
      cardDescription:
        "ಎಲ್ಲಾ ಗ್ರಾಹಕರ ಆದೇಶಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ. ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಆದೇಶದ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
      searchPlaceholder: "ಆದೇಶ ಐಡಿ ಅಥವಾ ಗ್ರಾಹಕರ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ...",
      orderId: "ಆದೇಶ ಐಡಿ",
      customer: "ಗ್ರಾಹಕ",
      status: "ಸ್ಥಿತಿ",
      date: "ದಿನಾಂಕ",
      total: "ಒಟ್ಟು",
      actions: "ಕ್ರಿಯೆಗಳು",
      trackLive: "ಲೈವ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
      dialogTitle: "ಆದೇಶ ಟ್ರ್ಯಾಕಿಂಗ್",
      dialogDescription:
        "ನಿಮ್ಮ ಆದೇಶಕ್ಕಾಗಿ ಲೈವ್ ಶಿಪ್ಪಿಂಗ್ ಮತ್ತು ವಿತರಣಾ ನವೀಕರಣಗಳು.",
      currentLocation: "ಪ್ರಸ್ತುತ ಸ್ಥಳ",
      reachedState: "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ತಲುಪಿದೆ",
      estimatedDelivery: "ಅಂದಾಜು ವಿತರಣೆ",
      shipmentHistory: "ಸಾಗಣೆ ಇತಿಹಾಸ",
      noDetails: "ಈ ಆದೇಶಕ್ಕಾಗಿ ಇನ್ನೂ ಯಾವುದೇ ಸಾಗಣೆ ವಿವರಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    },
    products: {
      title: "ಉತ್ಪನ್ನಗಳು",
      description:
        "ನಮ್ಮ ರೈತರಿಂದ ನೇರವಾಗಿ ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ಖರೀದಿಸಿ.",
      freshCarrots: "ತಾಜಾ ಕ್ಯಾರೆಟ್",
      kgPrice: "1 ಕೆಜಿ - ರೂ.20",
      addToCart: "ಕಾರ್ಟ್‍ಗೆ ಸೇರಿಸಿ",
      buyNow: "ಈಗ ಖರೀದಿಸಿ",
      dialogTitle: "ನಿಮ್ಮ ಆದೇಶವನ್ನು ಇರಿಸಿ",
      dialogDescription:
        "ಖರೀದಿ ಪೂರ್ಣಗೊಳಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
      nameLabel: "ಹೆಸರು",
      namePlaceholder: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು",
      emailLabel: "ಇಮೇಲ್ ಐಡಿ",
      emailPlaceholder: "you@example.com",
      mobileLabel: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "ವಿಳಾಸ",
      addressPlaceholder: "123 ಮುಖ್ಯ ರಸ್ತೆ, ನಗರ",
      countryLabel: "ದೇಶ",
      countryPlaceholder: "ಉದಾ. ಭಾರತ",
      stateLabel: "ರಾಜ್ಯ",
      statePlaceholder: "ಉದಾ. ಮಹಾರಾಷ್ಟ್ರ",
      districtLabel: "ಜಿಲ್ಲೆ",
      districtPlaceholder: "ಉದಾ. ಪುಣೆ",
      cancel: "ರದ್ದುಮಾಡಿ",
      placeOrder: "ಆದೇಶವನ್ನು ಇರಿಸಿ",
      orderSuccessTitle: "ಆದೇಶವನ್ನು ಇರಿಸಲಾಗಿದೆ!",
      orderSuccessDescription: "ನಿಮ್ಮ ಆದೇಶವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.",
      orderFailTitle: "ಆದೇಶ ವಿಫಲವಾಗಿದೆ",
      orderFailDescription: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
    },
    matchmaking: {
      title: "ರೈತ ಹೊಂದಾಣಿಕೆ",
      description: "ತಾಜಾ ಪದಾರ್ಥಗಳನ್ನು ಪಡೆಯಲು ರೈತರೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ.",
      specializesIn: "ವಿಶೇಷತೆ:",
      sendInquiry: "ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
      dialogTitle: "ಸಂಪರ್ಕಿಸಿ",
      dialogDescription: "ಅವರ ಉತ್ಪನ್ನಗಳ ಬಗ್ಗೆ ವಿಚಾರಿಸಲು ನೇರವಾಗಿ ಸಂದೇಶ ಕಳುಹಿಸಿ.",
      subjectLabel: "ವಿಷಯ",
      subjectPlaceholder: "ಉದಾ., ತಾಜಾ ಟೊಮೆಟೊಗಳ ಬಗ್ಗೆ ವಿಚಾರಣೆ",
      messageLabel: "ಸಂದೇಶ",
      messagePlaceholder: "ಹಾಯ್ {farmerName}, ನನಗೆ ಆಸಕ್ತಿ ಇದೆ...",
      cancel: "ರದ್ದುಮಾಡಿ",
      send: "ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
      inquirySuccessTitle: "ವಿಚಾರಣೆ ಕಳುಹಿಸಲಾಗಿದೆ!",
      inquirySuccessDescription:
        "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು {farmerName} ಗೆ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
    },
    faq: {
      title: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
      description: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಕೆಲವು ಉತ್ತರಗಳು ಇಲ್ಲಿವೆ.",
      cardTitle: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
      cardDescription:
        "ಕೆಳಗೆ ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳನ್ನು ಹುಡುಕಿ.",
    },
    marketing: {
      title: "ಮಾರ್ಕೆಟಿಂಗ್",
      description:
        "ನಿಮ್ಮ ಮಾರ್ಕೆಟಿಂಗ್ ಪ್ರಚಾರಗಳಿಗಾಗಿ ಉಪಕರಣಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆಗಳು.",
      comingSoon: "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
      comingSoonDescription:
        "ಈ ವಿಭಾಗವು ನಿರ್ಮಾಣ ಹಂತದಲ್ಲಿದೆ. ರೋಚಕ ಹೊಸ ಮಾರ್ಕೆಟಿಂಗ್ ಉಪಕರಣಗಳಿಗಾಗಿ ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ!",
      workingHard:
        "ಪ್ರಚಾರ ಟ್ರ್ಯಾಕಿಂಗ್, ವಿಶ್ಲೇಷಣೆಗಳು ಮತ್ತು ಪ್ರಚಾರದ ಉಪಕರಣಗಳಂತಹ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ನಿಮಗೆ ತರಲು ನಾವು ಶ್ರಮಿಸುತ್ತಿದ್ದೇವೆ.",
    },
  },
  Bengali: {
    tagline: "কৃষকদের ক্ষমতায়ন, সতেজতা সরবরাহ",
    quote: "কৃষিতে প্রাণ সঞ্চার করছি",

    joinCommunity: "আমাদের সম্প্রদায়ে যোগ দিন",
    roles: {
      farmer: {
        name: "কৃষক",
        description:
          "আপনার পণ্য সরাসরি বিক্রি করতে আমাদের নেটওয়ার্কে যোগ দিন।",
      },
      customer: {
        name: "গ্রাহক",
        description: "তাজা, জৈব পণ্য আপনার দোরগোড়ায় পৌঁছে দেওয়া হয়।",
      },
      hub: {
        name: "হাব",
        description:
          "লজিস্টিক পরিচালনা করুন এবং কৃষকদের গ্রাহকদের সাথে সংযুক্ত করুন।",
      },
      restaurant: {
        name: "রেস্তোরাঁ",
        description: "স্থানীয় খামার থেকে সরাসরি তাজা উপাদান সংগ্রহ করুন।",
      },
    },
    continue: "চালিয়ে যান",
    ourMission: "আমাদের লক্ষ্য",
    missionStatement:
      "মনবাসম আমাদের বিশ্বস্ত হাব নেটওয়ার্কের মাধ্যমে আপনাকে স্থানীয় কৃষকদের সাথে সরাসরি সংযুক্ত করে, টেকসই কৃষিকে সমর্থন করার সময় আপনি তাজা জৈব পণ্য পান তা নিশ্চিত করে।",
    footer: "সমস্ত অধিকার সংরক্ষিত।",
    sidebar: {
      dashboard: "ড্যাশবোর্ড",
      profile: "প্রোফাইল",
      orders: "অর্ডার",
      products: "পণ্য",
      track: "অর্ডার ট্র্যাক করুন",
      matchmaking: "ম্যাচমেকিং",
      voiceAssistant: "ভয়েস সহকারী",
      marketing: "বিপণন",
      faq: "FAQ",
    },
    signOut: {
      button: "সাইন আউট",
      title: "সাইন আউট করা হয়েছে",
      description: "আপনি সফলভাবে সাইন আউট হয়েছেন।",
      errorTitle: "সাইন আউট ব্যর্থ হয়েছে",
    },
    auth: {
      welcome: "মনবাসম-এ স্বাগতম",
      getStarted: "শুরু করতে সাইন ইন করুন বা একটি অ্যাকাউন্ট তৈরি করুন।",
      login: "লগইন",
      register: "নিবন্ধন করুন",
      emailPassword: "ইমেল এবং পাসওয়ার্ড",
      farmerFaceSignIn: "কৃষক ফেস সাইন-ইন",
      emailLabel: "ইমেল",
      passwordLabel: "পাসওয়ার্ড",
      forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
      forgotPasswordTitle: "পাসওয়ার্ড ভুলে গেছেন",
      forgotPasswordDesc: "আপনার ইমেল লিখুন এবং আমরা একটি রিসেট লিঙ্ক পাঠাব।",
      sendResetLink: "রিসেট লিঙ্ক পাঠান",
      cancel: "বাতিল করুন",
      signIn: "সাইন ইন করুন",
      iamA: "আমি একজন...",
      customer: "গ্রাহক",
      farmer: "কৃষক",
      faceReg: "ফেস রেজিস্ট্রেশন",
      faceRegDesc:
        "আপনার মুখ ক্যামেরায় কেন্দ্র করুন এবং ক্যাপচারে ক্লিক করুন।",
      capturePhoto: "ছবি ক্যাপচার করুন",
      photoCaptured: "ছবি সফলভাবে ক্যাপচার করা হয়েছে!",
      retakePhoto: "ছবি আবার তুলুন",
      usernameLabel: "ব্যবহারকারীর নাম",
      phoneLabel: "ফোন নম্বর",
      confirmPasswordLabel: "পাসওয়ার্ড নিশ্চিত করুন",
      createAccount: "অ্যাকাউন্ট তৈরি করুন",
      hubPortal: "হাব পোর্টাল",
      hubDesc: "লজিস্টিক পরিচালনা করুন এবং আমাদের নেটওয়ার্ক সংযোগ করুন।",
      branchNameLabel: "শাখার নাম",
      branchIdLabel: "শাখা আইডি",
      hubAdminEmailLabel: "হাব অ্যাডমিন ইমেল",
      registerHub: "হাব নিবন্ধন করুন",
      restaurantPortal: "রেস্তোরাঁ পোর্টাল",
      restaurantDesc:
        "আপনার অ্যাকাউন্ট অ্যাক্সেস করুন বা আপনার রেস্তোরাঁ নিবন্ধন করুন।",
      restaurantIdLabel: "রেস্তোরাঁ আইডি",
      restaurantIdPlaceholder: "আপনার অনন্য রেস্তোরাঁ আইডি",
      forgotPasswordRestaurantDesc:
        "পাসওয়ার্ড রিসেট লিঙ্ক পেতে আপনার রেস্তোরাঁ আইডি বা ইমেল লিখুন।",
      restaurantIdOrEmailLabel: "রেস্তোরাঁ আইডি বা ইমেল",
      restaurantIdOrEmailPlaceholder: "আইডি বা ইমেল",
      restaurantNameLabel: "রেস্তোরাঁর নাম",
      restaurantEmailLabel: "রেস্তোরাঁর ইমেল",
      restaurantPhoneLabel: "রেস্তোরাঁর ফোন",
      locationLabel: "অবস্থান",
      registerRestaurant: "রেস্তোরাঁ নিবন্ধন করুন",
    },
    dashboard: {
      title: "ড্যাশবোর্ড",
      welcome: "আবারো স্বাগতম",
      loading: "লোড হচ্ছে...",
      totalRevenue: "মোট রাজস্ব",
      fromLastMonth: "গত মাস থেকে",
      newCustomers: "নতুন গ্রাহক",
      productsSold: "বিক্রি হওয়া পণ্য",
      yourProfile: "আপনার প্রোফাইল",
      viewProfile: "আপনার প্রোফাইল দেখুন",
    },
    profile: {
      title: "আমার প্রোফাইল",
      description: "আপনার অ্যাকাউন্টের বিবরণ দেখুন এবং পরিচালনা করুন।",
      cardTitle: "ব্যবহারকারীর তথ্য",
      cardDescription: "আপনার ব্যক্তিগত এবং অ্যাকাউন্টের বিবরণ।",
      editProfile: "প্রোফাইল সম্পাদনা করুন",
      editDialogTitle: "প্রোফাইল সম্পাদনা করুন",
      editDialogDescription:
        "এখানে আপনার প্রোফাইলে পরিবর্তন করুন। সম্পন্ন হলে সংরক্ষণ ক্লিক করুন।",
      profilePicture: "প্রোফাইল ছবি",
      branchName: "শাখার নাম",
      username: "ব্যবহারকারীর নাম",
      email: "ইমেল",
      phone: "ফোন নম্বর",
      saveChanges: "পরিবর্তন সংরক্ষণ করুন",
      cancel: "বাতিল করুন",
      updateSuccessTitle: "সফল",
      updateSuccessDescription: "আপনার প্রোফাইল সফলভাবে আপডেট করা হয়েছে।",
      updateErrorTitle: "আপডেট ব্যর্থ হয়েছে",
      loadError: "ব্যবহারকারীর প্রোফাইল লোড করা যায়নি।",
      emailLabel: "ইমেল",
      phoneLabel: "ফোন",
      branchIdLabel: "শাখা আইডি",
      userTypeLabel: "ব্যবহারকারীর প্রকার",
      memberSinceLabel: "সদস্য",
      noProfileData: "কোন প্রোফাইল ডেটা পাওয়া যায়নি।",
    },
    orders: {
      title: "অর্ডার",
      description: "এখানে সাম্প্রতিক সমস্ত অর্ডারের একটি তালিকা রয়েছে।",
      cardTitle: "সমস্ত অর্ডার",
      cardDescription:
        "সমস্ত গ্রাহক অর্ডার পর্যালোচনা এবং পরিচালনা করুন। বিশদ দেখতে একটি অর্ডারে ক্লিক করুন।",
      searchPlaceholder: "অর্ডার আইডি বা গ্রাহকের নাম দিয়ে অনুসন্ধান করুন...",
      orderId: "অর্ডার আইডি",
      customer: "গ্রাহক",
      status: "স্থিতি",
      date: "তারিখ",
      total: "মোট",
      actions: "কর্ম",
      trackLive: "লাইভ ট্র্যাক করুন",
      dialogTitle: "অর্ডার ট্র্যাকিং",
      dialogDescription: "আপনার অর্ডারের জন্য লাইভ শিপিং এবং ডেলিভারি আপডেট।",
      currentLocation: "বর্তমান অবস্থান",
      reachedState: "আপনার রাজ্যে পৌঁছেছে",
      estimatedDelivery: "আনুমানিক ডেলিভারি",
      shipmentHistory: "চালানের ইতিহাস",
      noDetails: "এই অর্ডারের জন্য এখনো কোন শিপিং বিবরণ উপলব্ধ নেই।",
    },
    products: {
      title: "পণ্য",
      description:
        "আমাদের কৃষকদের কাছ থেকে সরাসরি তাজা পণ্য ব্রাউজ করুন এবং কিনুন।",
      freshCarrots: "তাজা গাজর",
      kgPrice: "১ কেজি - ২০ টাকা",
      addToCart: "কার্টে যোগ করুন",
      buyNow: "এখনই কিনুন",
      dialogTitle: "আপনার অর্ডার দিন",
      dialogDescription: "ক্রয় সম্পূর্ণ করতে আপনার বিবরণ পূরণ করুন।",
      nameLabel: "নাম",
      namePlaceholder: "আপনার পুরো নাম",
      emailLabel: "ইমেল আইডি",
      emailPlaceholder: "you@example.com",
      mobileLabel: "মোবাইল নম্বর",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "হোয়াটসঅ্যাপ নম্বর",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "ঠিকানা",
      addressPlaceholder: "123 প্রধান রাস্তা, শহর",
      countryLabel: "দেশ",
      countryPlaceholder: "যেমন ভারত",
      stateLabel: "রাজ্য",
      statePlaceholder: "যেমন মহারাষ্ট্র",
      districtLabel: "জেলা",
      districtPlaceholder: "যেমন পুনে",
      cancel: "বাতিল করুন",
      placeOrder: "অর্ডার দিন",
      orderSuccessTitle: "অর্ডার দেওয়া হয়েছে!",
      orderSuccessDescription: "আপনার অর্ডার সফলভাবে জমা দেওয়া হয়েছে।",
      orderFailTitle: "অর্ডার ব্যর্থ হয়েছে",
      orderFailDescription: "কিছু একটা ভুল হয়েছে।",
    },
    matchmaking: {
      title: "কৃষক ম্যাচমেকিং",
      description: "তাজা উপাদান পেতে সরাসরি কৃষকদের সাথে সংযোগ স্থাপন করুন।",
      specializesIn: "বিশেষত্ব:",
      sendInquiry: "অনুসন্ধান পাঠান",
      dialogTitle: "যোগাযোগ",
      dialogDescription:
        "তাদের পণ্য সম্পর্কে জিজ্ঞাসা করতে সরাসরি একটি বার্তা পাঠান।",
      subjectLabel: "বিষয়",
      subjectPlaceholder: "যেমন, তাজা টমেটো সম্পর্কে জিজ্ঞাসা",
      messageLabel: "বার্তা",
      messagePlaceholder: "হাই {farmerName}, আমি আগ্রহী...",
      cancel: "বাতিল করুন",
      send: "অনুসন্ধান পাঠান",
      inquirySuccessTitle: "অনুসন্ধান পাঠানো হয়েছে!",
      inquirySuccessDescription:
        "আপনার বার্তা সফলভাবে {farmerName} এর কাছে পাঠানো হয়েছে।",
    },
    faq: {
      title: "প্রায়শই জিজ্ঞাসিত প্রশ্ন",
      description: "এখানে সাধারণ প্রশ্নের কিছু উত্তর দেওয়া হল।",
      cardTitle: "সাধারণ প্রশ্ন",
      cardDescription: "নীচে প্রায়শই জিজ্ঞাসিত প্রশ্নের উত্তর খুঁজুন।",
    },
    marketing: {
      title: "বিপণন",
      description: "আপনার বিপণন প্রচারের জন্য সরঞ্জাম এবং বিশ্লেষণ।",
      comingSoon: "শীঘ্রই আসছে",
      comingSoonDescription:
        "এই বিভাগটি নির্মাণাধীন। উত্তেজনাপূর্ণ নতুন বিপণন সরঞ্জামগুলির জন্য পরে আবার দেখুন!",
      workingHard:
        "আমরা আপনাকে প্রচারাভিযান ট্র্যাকিং, বিশ্লেষণ এবং প্রচারমূলক সরঞ্জামগুলির মতো বৈশিষ্ট্যগুলি সরবরাহ করার জন্য কঠোর পরিশ্রম করছি।",
    },
  },
  Arabic: {
    tagline: "تمكين المزارعين، وتوصيل المنتجات الطازجة",
    quote: "نبث الحياة في الزراعة",

    joinCommunity: "انضم إلى مجتمعنا",
    roles: {
      farmer: {
        name: "مزارع",
        description: "انضم إلى شبكتنا لبيع منتجاتك مباشرة.",
      },
      customer: {
        name: "عميل",
        description: "احصل على منتجات عضوية طازجة تصل إلى عتبة داركم.",
      },
      hub: {
        name: "مركز",
        description: "إدارة الخدمات اللوجستية وربط المزارعين بالعملاء.",
      },
      restaurant: {
        name: "مطعم",
        description: "احصل على المكونات الطازجة مباشرة من المزارع المحلية.",
      },
    },
    continue: "متابعة",
    ourMission: "مهمتنا",
    missionStatement:
      "تقوم مانفاسام بتوصيلك مباشرة بالمزارعين المحليين من خلال شبكة مراكزنا الموثوقة، مما يضمن حصولك على المنتجات العضوية الطازجة مع دعم الزراعة المستدامة.",
    footer: "كل الحقوق محفوظة.",
    sidebar: {
      dashboard: "لوحة القيادة",
      profile: "الملف الشخصي",
      orders: "الطلبات",
      products: "المنتجات",
      track: "تتبع الطلب",
      matchmaking: "التوفيق",
      voiceAssistant: "مساعد صوتي",
      marketing: "التسويق",
      faq: "التعليمات",
    },
    signOut: {
      button: "تسجيل الخروج",
      title: "تم تسجيل الخروج",
      description: "لقد تم تسجيل خروجك بنجاح.",
      errorTitle: "فشل تسجيل الخروج",
    },
    auth: {
      welcome: "مرحبًا بك في مانفاسام",
      getStarted: "للبدء، قم بتسجيل الدخول أو إنشاء حساب.",
      login: "تسجيل الدخول",
      register: "تسجيل",
      emailPassword: "البريد الإلكتروني وكلمة المرور",
      farmerFaceSignIn: "تسجيل دخول المزارع بالوجه",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      forgotPasswordTitle: "هل نسيت كلمة المرور",
      forgotPasswordDesc: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.",
      sendResetLink: "إرسال رابط إعادة التعيين",
      cancel: "إلغاء",
      signIn: "تسجيل الدخول",
      iamA: "أنا...",
      customer: "عميل",
      farmer: "مزارع",
      faceReg: "تسجيل الوجه",
      faceRegDesc: "ضع وجهك في وسط الكاميرا وانقر على التقاط.",
      capturePhoto: "التقاط صورة",
      photoCaptured: "تم التقاط الصورة بنجاح!",
      retakePhoto: "إعادة التقاط الصورة",
      usernameLabel: "اسم المستخدم",
      phoneLabel: "رقم الهاتف",
      confirmPasswordLabel: "تأكيد كلمة المرور",
      createAccount: "إنشاء حساب",
      hubPortal: "بوابة المركز",
      hubDesc: "إدارة الخدمات اللوجستية وربط شبكتنا.",
      branchNameLabel: "اسم الفرع",
      branchIdLabel: "معرف الفرع",
      hubAdminEmailLabel: "البريد الإلكتروني لمسؤول المركز",
      registerHub: "تسجيل المركز",
      restaurantPortal: "بوابة المطعم",
      restaurantDesc: "الوصول إلى حسابك أو تسجيل مطعمك.",
      restaurantIdLabel: "معرف المطعم",
      restaurantIdPlaceholder: "معرف المطعم الفريد الخاص بك",
      forgotPasswordRestaurantDesc:
        "أدخل معرف المطعم أو البريد الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.",
      restaurantIdOrEmailLabel: "معرف المطعم أو البريد الإلكتروني",
      restaurantIdOrEmailPlaceholder: "المعرف أو البريد الإلكتروني",
      restaurantNameLabel: "اسم المطعم",
      restaurantEmailLabel: "البريد الإلكتروني للمطعم",
      restaurantPhoneLabel: "هاتف المطعم",
      locationLabel: "الموقع",
      registerRestaurant: "تسجيل مطعم",
    },
    dashboard: {
      title: "لوحة القيادة",
      welcome: "مرحبًا بعودتك",
      loading: "جار التحميل...",
      totalRevenue: "إجمالي الإيرادات",
      fromLastMonth: "من الشهر الماضي",
      newCustomers: "عملاء جدد",
      productsSold: "المنتجات المباعة",
      yourProfile: "ملفك الشخصي",
      viewProfile: "عرض ملفك الشخصي",
    },
    profile: {
      title: "ملفي الشخصي",
      description: "عرض وإدارة تفاصيل حسابك.",
      cardTitle: "معلومات المستخدم",
      cardDescription: "تفاصيلك الشخصية وحسابك.",
      editProfile: "تعديل الملف الشخصي",
      editDialogTitle: "تعديل الملف الشخصي",
      editDialogDescription:
        "قم بإجراء تغييرات على ملفك الشخصي هنا. انقر فوق حفظ عند الانتهاء.",
      profilePicture: "الصورة الشخصية",
      branchName: "اسم الفرع",
      username: "اسم المستخدم",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      saveChanges: "حفظ التغييرات",
      cancel: "إلغاء",
      updateSuccessTitle: "نجاح",
      updateSuccessDescription: "تم تحديث ملفك الشخصي بنجاح.",
      updateErrorTitle: "فشل التحديث",
      loadError: "تعذر تحميل ملف تعريف المستخدم.",
      emailLabel: "البريد الإلكتروني",
      phoneLabel: "الهاتف",
      branchIdLabel: "معرف الفرع",
      userTypeLabel: "نوع المستخدم",
      memberSinceLabel: "عضو منذ",
      noProfileData: "لم يتم العثور على بيانات الملف الشخصي.",
    },
    orders: {
      title: "الطلبات",
      description: "فيما يلي قائمة بجميع الطلبات الأخيرة.",
      cardTitle: "جميع الطلبات",
      cardDescription:
        "مراجعة وإدارة جميع طلبات العملاء. انقر فوق طلب لعرض التفاصيل.",
      searchPlaceholder: "البحث عن طريق معرف الطلب أو اسم العميل...",
      orderId: "معرف الطلب",
      customer: "العميل",
      status: "الحالة",
      date: "التاريخ",
      total: "المجموع",
      actions: "الإجراءات",
      trackLive: "تتبع مباشر",
      dialogTitle: "تتبع الطلب",
      dialogDescription: "تحديثات الشحن والتسليم المباشرة لطلبك.",
      currentLocation: "الموقع الحالي",
      reachedState: "وصلت إلى ولايتك",
      estimatedDelivery: "التسليم المقدر",
      shipmentHistory: "سجل الشحن",
      noDetails: "لا توجد تفاصيل شحن متاحة لهذا الطلب حتى الآن.",
    },
    products: {
      title: "المنتجات",
      description: "تصفح وشراء المنتجات الطازجة مباشرة من مزارعينا.",
      freshCarrots: "جزر طازج",
      kgPrice: "1 كجم - 20 روبية",
      addToCart: "أضف إلى السلة",
      buyNow: "اشتر الآن",
      dialogTitle: "قدم طلبك",
      dialogDescription: "يرجى ملء التفاصيل الخاصة بك لإكمال عملية الشراء.",
      nameLabel: "الاسم",
      namePlaceholder: "اسمك الكامل",
      emailLabel: "معرف البريد الإلكتروني",
      emailPlaceholder: "you@example.com",
      mobileLabel: "رقم الجوال",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "رقم WhatsApp",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "العنوان",
      addressPlaceholder: "123 الشارع الرئيسي، المدينة",
      countryLabel: "البلد",
      countryPlaceholder: "مثل الهند",
      stateLabel: "الولاية",
      statePlaceholder: "مثل ماهاراشترا",
      districtLabel: "المنطقة",
      districtPlaceholder: "مثل بيون",
      cancel: "إلغاء",
      placeOrder: "قدم الطلب",
      orderSuccessTitle: "تم تقديم الطلب!",
      orderSuccessDescription: "تم تقديم طلبك بنجاح.",
      orderFailTitle: "فشل الطلب",
      orderFailDescription: "حدث خطأ ما.",
    },
    matchmaking: {
      title: "التوفيق بين المزارعين",
      description: "تواصل مباشرة مع المزارعين للحصول على المكونات الطازجة.",
      specializesIn: "متخصص في:",
      sendInquiry: "إرسال استفسار",
      dialogTitle: "اتصال",
      dialogDescription: "أرسل رسالة مباشرة للاستفسار عن منتجاتهم.",
      subjectLabel: "الموضوع",
      subjectPlaceholder: "على سبيل المثال، استفسار عن الطماطم الطازجة",
      messageLabel: "الرسالة",
      messagePlaceholder: "مرحبًا {farmerName}، أنا مهتم بـ...",
      cancel: "إلغاء",
      send: "إرسال استفسار",
      inquirySuccessTitle: "تم إرسال الاستفسار!",
      inquirySuccessDescription: "تم إرسال رسالتك بنجاح إلى {farmerName}.",
    },
    faq: {
      title: "الأسئلة المتداولة",
      description: "فيما يلي بعض الإجابات على الأسئلة الشائعة.",
      cardTitle: "الأسئلة الشائعة",
      cardDescription: "ابحث عن إجابات للأسئلة الأكثر شيوعًا أدناه.",
    },
    marketing: {
      title: "التسويق",
      description: "أدوات وتحليلات لحملاتك التسويقية.",
      comingSoon: "قريبا",
      comingSoonDescription:
        "هذا القسم قيد الإنشاء. تحقق مرة أخرى لاحقًا للحصول على أدوات تسويقية جديدة ومثيرة!",
      workingHard:
        "نحن نعمل بجد لنقدم لك ميزات مثل تتبع الحملات والتحليلات والأدوات الترويجية.",
    },
  },
  Urdu: {
    tagline: "کسانوں کو بااختیار بنانا، تازگی فراہم کرنا",
    quote: "زراعت میں جان ڈال رہے ہیں",

    joinCommunity: "ہماری کمیونٹی میں شامل ہوں",
    roles: {
      farmer: {
        name: "کسان",
        description:
          "اپنی پیداوار براہ راست فروخت کرنے کے لیے ہمارے نیٹ ورک میں شامل ہوں۔",
      },
      customer: {
        name: "گاہک",
        description: "تازہ، نامیاتی مصنوعات اپنی دہلیز پر حاصل کریں۔",
      },
      hub: {
        name: "مرکز",
        description: "لاجسٹکس کا نظم کریں اور کسانوں کو صارفین سے جوڑیں۔",
      },
      restaurant: {
        name: "ریستوراں",
        description: "مقامی فارموں سے براہ راست تازہ اجزاء حاصل کریں۔",
      },
    },
    continue: "جاری رکھیں",
    ourMission: "ہمارا مقصد",
    missionStatement:
      "منواسم آپ کو ہمارے قابل اعتماد مرکز نیٹ ورک کے ذریعے براہ راست مقامی کسانوں سے جوڑتا ہے، اس بات کو یقینی بناتا ہے کہ آپ پائیدار زراعت کی حمایت کرتے ہوئے تازہ ترین نامیاتی مصنوعات حاصل کریں۔",
    footer: "جملہ حقوق محفوظ ہیں۔",
    sidebar: {
      dashboard: "ڈیش بورڈ",
      profile: "پروفائل",
      orders: "آرڈرز",
      products: "مصنوعات",
      track: "آرڈر ٹریک کریں",
      matchmaking: " میچ میکنگ",
      voiceAssistant: "وائس اسسٹنٹ",
      marketing: "مارکیٹنگ",
      faq: "اکثر पूछे گئے سوالات",
    },
    signOut: {
      button: "সাইন আউট",
      title: "সাইন আউট করা হয়েছে",
      description: "আপনি সফলভাবে সাইন আউট হয়েছেন।",
      errorTitle: "সাইন আউট ব্যর্থ হয়েছে",
    },
    auth: {
      welcome: "منواسم میں خوش آمدید",
      getStarted: "شروع کرنے کے لیے سائن ان کریں یا ایک اکاؤنٹ بنائیں۔",
      login: "لاگ ان کریں",
      register: "رجسٹر کریں",
      emailPassword: "ای میل اور پاس ورڈ",
      farmerFaceSignIn: "کسان فیس سائن ان",
      emailLabel: "ای میل",
      passwordLabel: "پاس ورڈ",
      forgotPassword: "پاس ورڈ بھول گئے؟",
      forgotPasswordTitle: "پاس ورڈ بھول گئے",
      forgotPasswordDesc:
        "اپنا ای میل درج کریں اور ہم ایک ری سیٹ لنک بھیجیں گے۔",
      sendResetLink: "ری سیٹ لنک بھیجیں",
      cancel: "منسوخ کریں",
      signIn: "سائن ان کریں",
      iamA: "میں ایک...",
      customer: "گاہک",
      farmer: "کسان",
      faceReg: "چہرے کی رجسٹریشن",
      faceRegDesc: "اپنے چہرے کو کیمرے میں مرکز کریں اور کیپچر پر کلک کریں۔",
      capturePhoto: "تصویر کیپچر کریں",
      photoCaptured: "تصویر کامیابی سے کیپچر ہوگئی!",
      retakePhoto: "دوبارہ تصویر لیں",
      usernameLabel: "صارف نام",
      phoneLabel: "فون نمبر",
      confirmPasswordLabel: "پاس ورڈ کی تصدیق کریں",
      createAccount: "اکاؤنٹ بنائیں",
      hubPortal: "حب پورٹل",
      hubDesc: "لاجسٹکس کا نظم کریں اور ہمارے نیٹ ورک کو جوڑیں۔",
      branchNameLabel: "برانچ کا نام",
      branchIdLabel: "برانਚ آئی ڈی",
      hubAdminEmailLabel: "حب ایڈمن ای میل",
      registerHub: "حب رجسٹر کریں",
      restaurantPortal: "ریستوراں پورٹل",
      restaurantDesc:
        "اپنے اکاؤنٹ تک رسائی حاصل کریں یا اپنے ریستوراں کو رجسٹر کریں۔",
      restaurantIdLabel: "ریستوراں آئی ڈی",
      restaurantIdPlaceholder: "آپ کی منفرد ریستوراں آئی ڈی",
      forgotPasswordRestaurantDesc:
        "پاس ورڈ ری سیٹ لنک حاصل کرنے کے لیے اپنی ریستوراں آئی ڈی یا ای میل درج کریں۔",
      restaurantIdOrEmailLabel: "ریستوراں آئی ڈی یا ای میل",
      restaurantIdOrEmailPlaceholder: "آئی ڈی یا ای میل",
      restaurantNameLabel: "ریستوراں کا نام",
      restaurantEmailLabel: "ریستوراں ای میل",
      restaurantPhoneLabel: "ریستوراں فون",
      locationLabel: "مقام",
      registerRestaurant: "ریستوراں رجسٹر کریں",
    },
    dashboard: {
      title: "ڈیش بورڈ",
      welcome: "خوش آمدید",
      loading: "لوڈ ہو رہا ہے...",
      totalRevenue: "کل آمدنی",
      fromLastMonth: "پچھلے مہینے سے",
      newCustomers: "نئے گاہک",
      productsSold: "فروخت شدہ مصنوعات",
      yourProfile: "آپ کی پروفائل",
      viewProfile: "اپنی پروفائل دیکھیں",
    },
    profile: {
      title: "میری پروفائل",
      description: "اپنے اکاؤنٹ کی تفصیلات دیکھیں اور ان کا نظم کریں۔",
      cardTitle: "صارف کی معلومات",
      cardDescription: "آپ کی ذاتی اور اکاؤنٹ کی تفصیلات۔",
      editProfile: "پروفائل میں ترمیم کریں",
      editDialogTitle: "پروفائل میں ترمیم کریں",
      editDialogDescription:
        "اپنی پروفائل میں تبدیلیاں یہاں کریں۔ جب آپ کام کر لیں تو محفوظ کریں پر کلک کریں۔",
      profilePicture: "پروفائل تصویر",
      branchName: "برانچ کا نام",
      username: "صارف نام",
      email: "ای میل",
      phone: "فون نمبر",
      saveChanges: "تبدیلیاں محفوظ کریں",
      cancel: "منسوخ کریں",
      updateSuccessTitle: "کامیابی",
      updateSuccessDescription: "آپ کی پروفائل کامیابی سے اپ ڈیٹ ہو گئی ہے۔",
      updateErrorTitle: "اپ ڈیٹ ناکام",
      loadError: "صارف کی پروفائل لوڈ نہیں ہو سکی۔",
      emailLabel: "ای میل",
      phoneLabel: "فون",
      branchIdLabel: "برانچ آئی ڈی",
      userTypeLabel: "صارف کی قسم",
      memberSinceLabel: "رکنیت",
      noProfileData: "کوئی پروفائل ڈیٹا نہیں ملا۔",
    },
    orders: {
      title: "آرڈرز",
      description: "یہاں تمام حالیہ آرڈرز کی فہرست ہے۔",
      cardTitle: "تمام آرڈرز",
      cardDescription:
        "تمام کسٹمر آرڈرز کا جائزہ لیں اور ان کا نظم کریں۔ تفصیلات دیکھنے کے لیے کسی آرڈر پر کلک کریں۔",
      searchPlaceholder: "آرڈر آئی ڈی یا کسٹمر کے نام سے تلاش کریں...",
      orderId: "آرڈر آئی ڈی",
      customer: "کسٹمر",
      status: "حیثیت",
      date: "تاریخ",
      total: "کل",
      actions: "اعمال",
      trackLive: "لائیو ٹریک کریں",
      dialogTitle: "آرڈر ٹریکنگ",
      dialogDescription: "آپ کے آرڈر کے لیے لائیو شپنگ اور ڈیلیوری اپ ڈیٹس۔",
      currentLocation: "موجودہ مقام",
      reachedState: "آپ کی ریاست پہنچ گئی",
      estimatedDelivery: "تخمینی ڈیلیوری",
      shipmentHistory: "شپمنٹ کی تاریخ",
      noDetails: "اس آرڈر کے لیے ابھی تک کوئی شپنگ تفصیلات دستیاب نہیں ہیں۔",
    },
    products: {
      title: "مصنوعات",
      description:
        "ہمارے کسانوں سے براہ راست تازہ پیداوار براؤز کریں اور خریدیں۔",
      freshCarrots: "تازہ گاجر",
      kgPrice: "1 کلوگرام - 20 روپے",
      addToCart: "کارٹ میں شامل کریں",
      buyNow: "ابھی خریدیں",
      dialogTitle: "اپنا آرڈر دیں",
      dialogDescription:
        "خریداری مکمل کرنے کے لیے براہ کرم اپنی تفصیلات بھریں۔",
      nameLabel: "نام",
      namePlaceholder: "آپ کا پورا نام",
      emailLabel: "ای میل آئی ڈی",
      emailPlaceholder: "you@example.com",
      mobileLabel: "موبائل نمبر",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "واٹس ایپ نمبر",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "پتہ",
      addressPlaceholder: "123 مین اسٹریٹ، شہر",
      countryLabel: "ملک",
      countryPlaceholder: "مثال کے طور پر ہندوستان",
      stateLabel: "ریاست",
      statePlaceholder: "مثال کے طور پر مہاراشٹر",
      districtLabel: "ضلع",
      districtPlaceholder: "مثال کے طور پر پونے",
      cancel: "منسوخ کریں",
      placeOrder: "آرڈر دیں",
      orderSuccessTitle: "آرڈر دے دیا گیا!",
      orderSuccessDescription: "آپ کا آرڈر کامیابی سے جمع کر دیا گیا ہے۔",
      orderFailTitle: "آرڈر ناکام",
      orderFailDescription: "کچھ غلط ہو گیا۔",
    },
    matchmaking: {
      title: "کسان میچ میکنگ",
      description:
        "تازہ اجزاء حاصل کرنے کے لیے کسانوں سے براہ راست رابطہ کریں۔",
      specializesIn: "میں مہارت رکھتا ہے:",
      sendInquiry: "انکوائری بھیجیں",
      dialogTitle: "رابطہ کریں",
      dialogDescription:
        "ان کی پیداوار کے بارے میں پوچھ گچھ کرنے کے لیے براہ راست ایک پیغام بھیجیں۔",
      subjectLabel: "موضوع",
      subjectPlaceholder: "مثال کے طور پر، تازہ ٹماٹروں کے بارے میں انکوائری",
      messageLabel: "پیغام",
      messagePlaceholder: "ہیلو {farmerName}، مجھے دلچسپی ہے۔..",
      cancel: "منسوخ کریں",
      send: "انکوائरी بھیجیں",
      inquirySuccessTitle: "انکوائری بھیجی گئی!",
      inquirySuccessDescription:
        "آپ کا پیغام {farmerName} کو کامیابی سے بھیج دیا گیا ہے۔",
    },
    faq: {
      title: "اکثر پوچھے جانے والے سوالات",
      description: "یہاں عام سوالات کے کچھ جوابات ہیں۔",
      cardTitle: "عام سوالات",
      cardDescription:
        "ذیل میں اکثر پوچھے جانے والے سوالات کے جوابات تلاش کریں۔",
    },
    marketing: {
      title: "مارکیٹنگ",
      description: "آپ کی مارکیٹنگ مہموں کے لیے ٹولز اور تجزیات۔",
      comingSoon: " جلد آ رہا ہے۔",
      comingSoonDescription:
        "یہ سیکشن زیر تعمیر ہے۔ دلچسپ نئے مارکیٹنگ ٹولز کے لیے بعد میں دوبارہ چیک کریں۔!",
      workingHard:
        "ہم آپ کو مہم سے باخبر رہنے، تجزیات، اور پروموشنل ٹولز جیسی خصوصیات لانے کے لیے سخت محنت کر रहे ہیں۔",
    },
  },
  Srilanka: {
    tagline: "ගොවීන් සවිබල ගැන්වීම, නැවුම් බව ලබා දීම",
    quote: "කෘෂිකර්මයට ජීවය ලබා දෙමින්",

    joinCommunity: "අපගේ ප්‍රජාවට සම්බන්ධ වන්න",
    roles: {
      farmer: {
        name: "ගොවියා",
        description:
          "ඔබේ නිෂ්පාදන සෘජුවම විකිණීම සඳහා අපගේ ජාලයට සම්බන්ධ වන්න.",
      },
      customer: {
        name: "පාරිභෝගික",
        description: "නැවුම්, කාබනික නිෂ්පාදන ඔබේ දොරකඩටම ගෙන්වා ගන්න.",
      },
      hub: {
        name: "කේන්ද්‍රය",
        description:
          "ලොජිස්ටික්ස් කළමනාකරණය කර ගොවීන් පාරිಭෝගිකයන් හා සම්බන්ධ කරන්න.",
      },
      restaurant: {
        name: "ආපන ශාලාව",
        description: "දේශීය ගොවිපලවලින් නැවුම් අමුද්‍රව්‍ය සෘජුවම ලබා ගන්න.",
      },
    },
    continue: "ඉදිරියට යන්න",
    ourMission: "අපේ මෙහෙවර",
    missionStatement:
      "මන්වාasam අපගේ විශ්වාසවන්ත මධ්‍යස්ථාන ජාලය හරහා ඔබව දේශීය ගොවීන් සමඟ සෘජුවම සම්බන්ධ කරයි, තිරසාර කෘෂිකර්මාන්තයට සහාය දෙන අතරම ඔබට නැවුම්ම කාබනික නිෂ්පාදන ලැබෙන බව සහතික කරයි.",
    footer: "සියලුම හිමිකම් ඇවිරිණි.",
    sidebar: {
      dashboard: "แดชบอร์ด",
      profile: "පැතිකඩ",
      orders: "ใบสั่งซื้อ",
      products: "නිෂ්පාදන",
      track: " ট্র্যাক অর্ডার",
      matchmaking: "ගැලපීම",
      voiceAssistant: "හඬ සහායක",
      marketing: "අලෙවිකරණය",
      faq: "නිතර අසන පැන",
    },
    signOut: {
      button: "ออกจากระบบ",
      title: "ออกจากระบบแล้ว",
      description: "คุณออกจากระบบเรียบร้อยแล้ว",
      errorTitle: "การออกจากระบบล้มเหลว",
    },
    auth: {
      welcome: "මන්වාasam වෙත සාදරයෙන් පිළිගනිමු",
      getStarted: "ආරම්භ කිරීමට පුරනය වන්න හෝ ගිණුමක් සාදන්න.",
      login: "ඇතුල් වන්න",
      register: "ලියාපදිංචි වන්න",
      emailPassword: "විද්‍යುත් තැපෑල සහ මුරපදය",
      farmerFaceSignIn: "ගොවි මුහුණ පුරනය වීම",
      emailLabel: "විද්යුත් තැපෑල",
      passwordLabel: "මුරපදය",
      forgotPassword: "මුරපදය අමතක වුණා ද?",
      forgotPasswordTitle: "මුරපදය අමතක වුණා ද",
      forgotPasswordDesc:
        "ඔබගේ විද්‍යುත් තැපෑල ඇතුළත් කරන්න, අපි යළි පිහිටුවීමේ සබැඳියක් එවන්නෙමු.",
      sendResetLink: "යළි පිහිටුවීමේ සබැඳිය යවන්න",
      cancel: "අუা करें",
      signIn: "පුරනය වන්න",
      iamA: "මම...",
      customer: "ಗ್ರಾಹಕ",
      farmer: "ගොවියා",
      faceReg: "මුහුණු ලියාපදිංචිය",
      faceRegDesc: "ඔබගේ මුහුණ කැමරාවේ මැදට ගෙන ග්‍රහණය ක්ලිಕ್ කරන්න.",
      capturePhoto: "ඡායාරූපය ගන්න",
      photoCaptured: "ඡායාරූපය සාර්ථකව ග්‍රහණය කර ඇත!",
      retakePhoto: "ඡායාරූපය නැවත ගන්න",
      usernameLabel: "පරිශීලක නාමය",
      phoneLabel: "දුරකථන අංකය",
      confirmPasswordLabel: "මුරපදය තහවුරු කරන්න",
      createAccount: "ගිණුම තනන්න",
      hubPortal: "හබ් ද්වාරය",
      hubDesc: "ලොජිස්ටික් කළමනාකරණය කර අපගේ ජාලය සම්බන්ධ කරන්න.",
      branchNameLabel: "ශාඛාවේ නම",
      branchIdLabel: "ශාඛා හැඳුනුම්පත",
      hubAdminEmailLabel: "හබ් පරිපාලක විද්‍යುත් තැපෑල",
      registerHub: "හබ් ලියාපදිංචි කරන්න",
      restaurantPortal: "ආපනශාලා ද්වාරය",
      restaurantDesc:
        "ඔබගේ ගිණුමට පිවිසෙන්න හෝ ඔබගේ ආපනශාලාව ලියාපදිංචි කරන්න.",
      restaurantIdLabel: "ආපනශාලා හැඳුනුම්පත",
      restaurantIdPlaceholder: "ඔබගේ අනන්‍ය ආපනශාලා හැඳුනුම්පත",
      forgotPasswordRestaurantDesc:
        "මුරපද යළි පිහිටුවීමේ සබැඳියක් ලබා ගැනීමට ඔබගේ ආපනශාලා හැඳුනුම්පත හෝ විද්‍යುත් තැපෑල ඇතුළත් කරන්න.",
      restaurantIdOrEmailLabel: "ආපනශාලා හැඳුනුම්පත හෝ විද්‍යುත් තැපෑල",
      restaurantIdOrEmailPlaceholder: "හැඳුනුම්පත හෝ විද්‍යುත් තැපෑල",
      restaurantNameLabel: "ආපනශාලාවේ නම",
      restaurantEmailLabel: "ආපනශාලා විද්‍යುත් තැපෑල",
      restaurantPhoneLabel: "ආපනශාලා දුරකථනය",
      locationLabel: "ස්ථානය",
      registerRestaurant: "ආපනශාලාව ලියාපදිංචි කරන්න",
    },
    dashboard: {
      title: "แดชบอร์ด",
      welcome: "නැවතත් සාදරයෙන් පිළිගනිමු",
      loading: "පූරණය වෙමින්...",
      totalRevenue: "මුළු ආදායම",
      fromLastMonth: "පසුගිය මාසයේ සිට",
      newCustomers: "නව පාරිභෝගිකයින්",
      productsSold: "විකුණන ලද නිෂ්පාදන",
      yourProfile: "ඔබේ පැතිකඩ",
      viewProfile: "ඔබගේ පැතිකඩ බලන්න",
    },
    profile: {
      title: "මගේ පැතිකඩ",
      description: "ඔබගේ ගිණුම් විස්තර බලන්න සහ කළමනාකරණය කරන්න.",
      cardTitle: "පරිශීලක තොරතුරු",
      cardDescription: "ඔබගේ පුද්ගලික සහ ගිණුම් විස්තර.",
      editProfile: "පැතිකඩ සංස්කරණය කරන්න",
      editDialogTitle: "පැතිකඩ සංස්කරණය කරන්න",
      editDialogDescription:
        "ඔබගේ පැතිකඩෙහි වෙනස්කම් මෙහි සිදු කරන්න. ඔබ අවසන් වූ පසු සුරකින්න ක්ලිಕ್ කරන්න.",
      profilePicture: "පැතිකඩ පින්තූරය",
      branchName: "ශාඛාවේ නම",
      username: "පරිශීලක නාමය",
      email: "විද්යුත් තැපෑල",
      phone: "දුරකථන අංකය",
      saveChanges: "වෙනස්කම් සුරකින්න",
      cancel: "අუা करें",
      updateSuccessTitle: "සාර්ථකයි",
      updateSuccessDescription: "ඔබගේ පැතිකඩ සාර්ථකව යාවත්කාලීන කර ඇත.",
      updateErrorTitle: "යාවත්කාලීන කිරීම අසාර්ථක විය",
      loadError: "පරිශීලක පැතිකඩ පැටවීමට නොහැකි විය.",
      emailLabel: "විද්යුත් තැපෑල",
      phoneLabel: "දුරකථනය",
      branchIdLabel: "ශාඛා හැඳුනුම්පත",
      userTypeLabel: "පරිශීලක වර්ගය",
      memberSinceLabel: "සිට සාමාජික",
      noProfileData: "පැතිකඩ දත්ත හමු නොවීය.",
    },
    orders: {
      title: "ใบสั่งซื้อ",
      description: "මෑත කාලීන සියලුම ඇණවුම් ලැයිස්තුවක් මෙන්න.",
      cardTitle: "සියලුම ඇණවුම්",
      cardDescription:
        "සියලුම පාරිභෝගික ඇණවුම් සමාලෝචනය කර කළමනාකරණය කරන්න. විස්තර බැලීමට ඇණවුමක් මත ක්ලිಕ್ කරන්න.",
      searchPlaceholder: "ඇණවුම් හැඳුනුම්පත හෝ පාරිභෝගික නාමය මගින් සොයන්න...",
      orderId: "ඇණවුම් හැඳුනුම්පත",
      customer: "පාරිභෝගික",
      status: "තත්ත්වය",
      date: "දිනය",
      total: "එකතුව",
      actions: "ක්‍රියා",
      trackLive: "සජීවීව නිරීක්ෂණය කරන්න",
      dialogTitle: "ඇණවුම් ලුහුබැඳීම",
      dialogDescription:
        "ඔබගේ ඇණවුම සඳහා සජීವී නැව්ගත කිරීමේ සහ බෙදා හැරීමේ යාවත්කාලීන කිරීම්.",
      currentLocation: "වත්මන් ස්ථානය",
      reachedState: "ඔබගේ ප්‍රාන්තයට ළඟා විය",
      estimatedDelivery: "ඇස්තමේන්තුගත බෙදාහැරීම",
      shipmentHistory: "නැව්ගත කිරීමේ ඉතිහාසය",
      noDetails: "මෙම ඇණවුම සඳහා තවමත් නැව්ගත කිරීමේ විස්තර නොමැත.",
    },
    products: {
      title: "නිෂ්පාදන",
      description:
        "අපගේ ගොვීන්ගෙන් සෘජුවම නැවුම් නිෂ්පාදන බ්‍රවුස් කර මිලදී ගන්න.",
      freshCarrots: "නැවුම් කැරට්",
      kgPrice: "1kg - රු.20",
      addToCart: "කරත්තයට එකතු කරන්න",
      buyNow: "දැන් මිලදී ගන්න",
      dialogTitle: "ඔබගේ ඇණවුම ලබා දෙන්න",
      dialogDescription:
        "මිලදී ගැනීම සම්පූර්ණ කිරීම සඳහා කරුණාකර ඔබගේ විස්තර පුරවන්න.",
      nameLabel: "නම",
      namePlaceholder: "ඔබගේ සම්පූර්ණ නම",
      emailLabel: "විද්‍යුත් තැපැල් හැඳුනුම්පත",
      emailPlaceholder: "you@example.com",
      mobileLabel: "ජංගම දුරකථන අංකය",
      mobilePlaceholder: "123-456-7890",
      whatsappLabel: "WhatsApp අංකය",
      whatsappPlaceholder: "123-456-7890",
      addressLabel: "ලිපිනය",
      addressPlaceholder: "123 ප්‍රධාන වීදිය, නගරය",
      countryLabel: "රට",
      countryPlaceholder: "උදා. ඉන්දියාව",
      stateLabel: "ප්‍රාන්තය",
      statePlaceholder: "උදා. මහාරාෂ්ට්‍ර",
      districtLabel: "දිස්ත්‍රික්කය",
      districtPlaceholder: "උදා. පූනේ",
      cancel: "අუা करें",
      placeOrder: "ඇණවුම ලබා දෙන්න",
      orderSuccessTitle: "ඇණවුම ලබා දී ඇත!",
      orderSuccessDescription: "ඔබගේ ඇණවුම සාර්ථකව ඉදිරිපත් කර ඇත.",
      orderFailTitle: "ඇණවුම අසාර්ථක විය",
      orderFailDescription: "යම් දෙයක් වැරදී ඇත.",
    },
    matchmaking: {
      title: "ගොವಿ ගැලපීම",
      description:
        "නැවුම් අමුද්‍රව්‍ය ලබා ගැනීමට ගොවීන් සමඟ සෘජුවම සම්බන්ධ වන්න.",
      specializesIn: "විශේෂඥ:",
      sendInquiry: "විමසීමක් යවන්න",
      dialogTitle: "සම්බන්ධ වන්න",
      dialogDescription: "ඔවුන්ගේ නිෂ්පාදන ගැන විමසීමට සෘජුවම පණිවිඩයක් යවන්න.",
      subjectLabel: "විෂය",
      subjectPlaceholder: "උදා., නැවුම් තක්කාලි පිළිබඳ විමසීම",
      messageLabel: "පණිවිඩය",
      messagePlaceholder: "හායි {farmerName}, මම කැමතියි...",
      cancel: "අუা करें",
      send: "විමසීමක් යවන්න",
      inquirySuccessTitle: "විමසීම යවා ඇත!",
      inquirySuccessDescription:
        "ඔබගේ පණිවිඩය {farmerName} වෙත සාර්ථකව යවා ඇත.",
    },
    faq: {
      title: "නිතර අසන පැන",
      description: "පොදු ප්‍රශ්න සඳහා පිළිතුරු කිහිපයක් මෙහි දැක්වේ.",
      cardTitle: "පොදු ප්‍රශ්න",
      cardDescription: "පහත දැක්වෙන නිතර අසන ප්‍රශ්න සඳහා පිළිතුරු සොයන්න.",
    },
    marketing: {
      title: "අලෙවිකරණය",
      description: "ඔබගේ අලෙවිකරණ ව්‍යාපාර සඳහා මෙවලම් සහ විශ්ලේෂණ.",
      comingSoon: "ඉක්මනින් පැමිණේ",
      comingSoonDescription:
        "මෙම කොටස ඉදිවෙමින් පවතී. සිත් ඇදගන්නාසුළු නව අලෙවිකරණ මෙවලම් සඳහා පසුව නැවත පරීක්ෂා කරන්න!",
      workingHard:
        "ප්‍රචාරක ලුහුබැඳීම, විශ්ලේෂණ සහ ප්‍රවර්ධන මෙවලම් වැනි විශේෂාංග ඔබට ගෙන ඒමට අපි වෙහෙස මහන්සි වී වැඩ කරමු.",
    },
  },
};

export const languages = Object.keys(translations);

type Language = keyof typeof translations;

interface LanguageContextType {
  selectedLanguage: Language;
  setSelectedLanguage: (language: Language) => void;
  t: (typeof translations)[Language];
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Initialize language from localStorage if available
const initializeLanguage = (): Language => {
  // Always return English during SSR to prevent hydration mismatches
  if (typeof window === "undefined") {
    return "English";
  }

  try {
    const storedLanguage = localStorage.getItem("manvaasam-language") as Language;
    if (storedLanguage && translations[storedLanguage]) {
      return storedLanguage;
    }
  } catch (error) {
    console.warn("Error reading localStorage:", error);
  }
  return "English";
};
export const LanguageProvider = ({
  children,
  initialLanguage,
}: {
  children: ReactNode;
  initialLanguage?: Language;
}) => {
  // Simple initialization - prioritize localStorage over everything
  const [selectedLanguage, setSelectedLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("manvaasam-language") as Language;
      if (stored && translations[stored]) {
        return stored;
      }
    }
    return initialLanguage && translations[initialLanguage] ? initialLanguage : "English";
  });

  // Simple effect to sync on mount
  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("manvaasam-language") as Language;
      if (stored && translations[stored] && stored !== selectedLanguage) {
        setSelectedLanguage(stored);
      }
    }
  }, []);

  // Listen for storage changes
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === "manvaasam-language" && e.newValue && translations[e.newValue as Language]) {
        setSelectedLanguage(e.newValue as Language);
      }
    };

    window.addEventListener("storage", handleStorageChange);
    return () => window.removeEventListener("storage", handleStorageChange);
  }, []);

  const handleSetLanguage = (language: Language) => {
    setSelectedLanguage(language);
    
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem("manvaasam-language", language);
        
        const expires = new Date();
        expires.setFullYear(expires.getFullYear() + 1);
        document.cookie = `manvaasam-language=${language};path=/;expires=${expires.toUTCString()};SameSite=Lax`;
        
        // Notify other tabs
        window.dispatchEvent(
          new StorageEvent("storage", {
            key: "manvaasam-language",
            newValue: language,
            storageArea: localStorage,
          })
        );
      } catch (error) {
        console.warn("Could not save language preference:", error);
      }
    }
  };

  const t = translations[selectedLanguage] || translations["English"];

  const contextValue = React.useMemo(
    () => ({ selectedLanguage, setSelectedLanguage: handleSetLanguage, t }),
    [selectedLanguage, t]
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
