
"use client";

import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

export const translations = {
  English: {
    tagline: "Empowering Farmers, Delivering Freshness",
    joinCommunity: "Join Our Community",
    roles: {
      farmer: {
        name: "Farmer",
        description: "Join our network to sell your produce directly.",
      },
      customer: {
        name: "Customer",
        description: "Get fresh, organic products delivered to your doorstep.",
      },
      hub: {
        name: "Hub",
        description: "Manage logistics and connect farmers to customers.",
      },
      restaurant: {
        name: "Restaurant",
        description: "Source fresh ingredients directly from local farms.",
      },
    },
    continue: "Continue",
    ourMission: "Our Mission",
    missionStatement: "Manvaasam connects you directly with local farmers through our trusted hub network, ensuring you receive the freshest organic products while supporting sustainable agriculture.",
    footer: "All rights reserved.",
    sidebar: {
      dashboard: "Dashboard",
      profile: "Profile",
      orders: "Orders",
      products: "Products",
      track: "Track Order",
      matchmaking: "Matchmaking",
      voiceAssistant: "Voice Assistant",
      marketing: "Marketing",
      faq: "FAQ",
    },
    signOut: {
      button: "Sign Out",
      title: "Signed Out",
      description: "You have been successfully signed out.",
      errorTitle: "Sign Out Failed"
    },
    auth: {
      welcome: "Welcome to Manvaasam",
      getStarted: "Sign in or create an account to get started.",
      login: "Login",
      register: "Register",
      emailPassword: "Email & Password",
      farmerFaceSignIn: "Farmer Face Sign-In",
      emailLabel: "Email",
      passwordLabel: "Password",
      forgotPassword: "Forgot Password?",
      forgotPasswordTitle: "Forgot Password",
      forgotPasswordDesc: "Enter your email and we'll send a reset link.",
      sendResetLink: "Send Reset Link",
      cancel: "Cancel",
      signIn: "Sign In",
      iamA: "I am a...",
      customer: "Customer",
      farmer: "Farmer",
      faceReg: "Face Registration",
      faceRegDesc: "Center your face in the camera and click capture.",
      capturePhoto: "Capture Photo",
      photoCaptured: "Photo captured successfully!",
      retakePhoto: "Retake Photo",
      usernameLabel: "Username",
      phoneLabel: "Phone Number",
      confirmPasswordLabel: "Confirm Password",
      createAccount: "Create Account",
      hubPortal: "Hub Portal",
      hubDesc: "Manage logistics and connect our network.",
      branchNameLabel: "Branch Name",
      branchIdLabel: "Branch ID",
      hubAdminEmailLabel: "Hub Admin Email",
      registerHub: "Register Hub",
      restaurantPortal: "Restaurant Portal",
      restaurantDesc: "Access your account or register your restaurant.",
      restaurantIdLabel: "Restaurant ID",
      restaurantIdPlaceholder: "Your unique Restaurant ID",
      forgotPasswordRestaurantDesc: "Enter your Restaurant ID or email to receive a password reset link.",
      restaurantIdOrEmailLabel: "Restaurant ID or Email",
      restaurantIdOrEmailPlaceholder: "ID or email",
      restaurantNameLabel: "Restaurant Name",
      restaurantEmailLabel: "Restaurant Email",
      restaurantPhoneLabel: "Restaurant Phone",
      locationLabel: "Location",
      registerRestaurant: "Register Restaurant",
    }
  },
  Tamil: {
    tagline: "விவசாயிகளை மேம்படுத்துதல், புத்துணர்ச்சியை வழங்குதல்",
    joinCommunity: "எங்கள் சமூகத்தில் சேரவும்",
    roles: {
      farmer: {
        name: "விவசாயி",
        description: "உங்கள் விளைபொருட்களை நேரடியாக விற்க எங்கள் நெட்வொர்க்கில் சேரவும்.",
      },
      customer: {
        name: "வாடிக்கையாளர்",
        description: "புதிய, ஆர்கானிக் பொருட்களை உங்கள் வீட்டு வாசலில் பெறுங்கள்.",
      },
      hub: {
        name: "மையம்",
        description: "விநியோகத்தை நிர்வகித்து விவசாயிகளை வாடிக்கையாளர்களுடன் இணைக்கவும்.",
      },
      restaurant: {
        name: "உணவகம்",
        description: "உள்ளூர் பண்ணைகளிலிருந்து நேரடியாக புதிய பொருட்களைப் பெறுங்கள்.",
      },
    },
    continue: "தொடரவும்",
    ourMission: "எங்கள் நோக்கம்",
    missionStatement: "மன்வாசம் உங்களை உள்ளூர் விவசாயிகளுடன் எங்கள் நம்பகமான மைய நெட்வொர்க் மூலம் நேரடியாக இணைக்கிறது, நிலையான விவசாயத்தை ஆதரிக்கும் அதே வேளையில் புத்துணர்ச்சியான ஆர்கானிக் தயாரிப்புகளைப் பெறுவதை உறுதி செய்கிறது.",
    footer: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    sidebar: {
      dashboard: "முகப்பு",
      profile: "சுயவிவரம்",
      orders: "ஆர்டர்கள்",
      products: "பொருட்கள்",
      track: "ஆர்டரைக் கண்காணிக்கவும்",
      matchmaking: "பொருத்தம்",
      voiceAssistant: "குரல் உதவியாளர்",
      marketing: "சந்தைப்படுத்தல்",
      faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    },
    signOut: {
      button: "வெளியேறு",
      title: "வெளியேறப்பட்டது",
      description: "நீங்கள் வெற்றிகரமாக வெளியேறிவிட்டீர்கள்.",
      errorTitle: "வெளியேற முடியவில்லை"
    },
    auth: {
      welcome: "மன்வாசத்திற்கு வரவேற்கிறோம்",
      getStarted: "தொடங்குவதற்கு உள்நுழையவும் அல்லது ஒரு கணக்கை உருவாக்கவும்.",
      login: "உள்நுழை",
      register: "பதிவு செய்க",
      emailPassword: "மின்னஞ்சல் & கடவுச்சொல்",
      farmerFaceSignIn: "விவசாயி முக உள்நுழைவு",
      emailLabel: "மின்னஞ்சல்",
      passwordLabel: "கடவுச்சொல்",
      forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
      forgotPasswordTitle: "கடவுச்சொல்லை மறந்துவிட்டீர்களா",
      forgotPasswordDesc: "உங்கள் மின்னஞ்சலை உள்ளிடவும், நாங்கள் ஒரு மீட்டமைப்பு இணைப்பை அனுப்புவோம்.",
      sendResetLink: "மீட்டமைப்பு இணைப்பை அனுப்பு",
      cancel: "ரத்துசெய்",
      signIn: "உள்நுழைக",
      iamA: "நான் ஒரு...",
      customer: "வாடிக்கையாளர்",
      farmer: "விவசாயி",
      faceReg: "முக பதிவு",
      faceRegDesc: "உங்கள் முகத்தை கேமராவில் மையப்படுத்தி, பிடி என்பதைக் கிளிக் செய்யவும்.",
      capturePhoto: "புகைப்படம் எடு",
      photoCaptured: "புகைப்படம் வெற்றிகரமாக எடுக்கப்பட்டது!",
      retakePhoto: "மீண்டும் புகைப்படம் எடு",
      usernameLabel: "பயனர்பெயர்",
      phoneLabel: "தொலைபேசி எண்",
      confirmPasswordLabel: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
      createAccount: "கணக்கை உருவாக்கு",
      hubPortal: "மையம் போர்டல்",
      hubDesc: "தளவாடங்களை நிர்வகிக்கவும் மற்றும் எங்கள் நெட்வொர்க்கை இணைக்கவும்.",
      branchNameLabel: "கிளை பெயர்",
      branchIdLabel: "கிளை ஐடி",
      hubAdminEmailLabel: "மைய நிர்வாகி மின்னஞ்சல்",
      registerHub: "மையத்தை பதிவு செய்யுங்கள்",
      restaurantPortal: "உணவக போர்டல்",
      restaurantDesc: "உங்கள் கணக்கை அணுகவும் அல்லது உங்கள் உணவகத்தை பதிவு செய்யவும்.",
      restaurantIdLabel: "உணவக ஐடி",
      restaurantIdPlaceholder: "உங்கள் தனிப்பட்ட உணவக ஐடி",
      forgotPasswordRestaurantDesc: "கடவுச்சொல் மீட்டமைப்பு இணைப்பைப் பெற உங்கள் உணவக ஐடி அல்லது மின்னஞ்சலை உள்ளிடவும்.",
      restaurantIdOrEmailLabel: "உணவக ஐடி அல்லது மின்னஞ்சல்",
      restaurantIdOrEmailPlaceholder: "ஐடி அல்லது மின்னஞ்சல்",
      restaurantNameLabel: "உணவகத்தின் பெயர்",
      restaurantEmailLabel: "உணவக மின்னஞ்சல்",
      restaurantPhoneLabel: "உணவக தொலைபேசி",
      locationLabel: "இடம்",
      registerRestaurant: "உணவகத்தை பதிவு செய்யுங்கள்",
    }
  },
  Malayalam: {
    tagline: "കർഷകരെ ശാക്തീകരിക്കുന്നു, പുതുമ നൽകുന്നു",
    joinCommunity: "ഞങ്ങളുടെ കമ്മ്യൂണിറ്റിയിൽ ചേരുക",
    roles: {
      farmer: {
        name: "കർഷകൻ",
        description: "നിങ്ങളുടെ ഉൽപ്പന്നങ്ങൾ നേരിട്ട് വിൽക്കാൻ ഞങ്ങളുടെ നെറ്റ്‌വർക്കിൽ ചേരുക.",
      },
      customer: {
        name: "ഉപഭോക്താവ്",
        description: "പുതിയ, ഓർഗാനിക് ഉൽപ്പന്നങ്ങൾ നിങ്ങളുടെ വീട്ടുവാതിൽക്കൽ എത്തിക്കുക.",
      },
      hub: {
        name: "ഹബ്",
        description: "ലോജിസ്റ്റിക്സ് നിയന്ത്രിക്കുക, കർഷകരെ ഉപഭോക്താക്കളുമായി ബന്ധിപ്പിക്കുക.",
      },
       restaurant: {
        name: "റെസ്റ്റോറന്റ്",
        description: "പ്രാദേശിക ഫാമുകളിൽ നിന്ന് നേരിട്ട് പുതിയ ചേരുവകൾ നേടുക.",
      },
    },
    continue: "തുടരുക",
    ourMission: "ഞങ്ങളുടെ ദൗത്യം",
    missionStatement: "സുസ്ഥിരമായ കൃഷിയെ പിന്തുണച്ചുകൊണ്ട് നിങ്ങൾക്ക് ഏറ്റവും പുതിയ ഓർഗാനിക് ഉൽപ്പന്നങ്ങൾ ലഭിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കിക്കൊണ്ട് ഞങ്ങളുടെ വിശ്വസ്ത ഹബ് നെറ്റ്‌വർക്ക് വഴി മൻവാസം നിങ്ങളെ പ്രാദേശിക കർഷകരുമായി നേരിട്ട് ബന്ധിപ്പിക്കുന്നു.",
    footer: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
    sidebar: {
      dashboard: "ഡാഷ്ബോർഡ്",
      profile: "പ്രൊഫൈൽ",
      orders: "ഓർഡറുകൾ",
      products: "ഉൽപ്പന്നങ്ങൾ",
      track: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
      matchmaking: "മാച്ച് മേക്കിംഗ്",
      voiceAssistant: "വോയിസ് അസിസ്റ്റന്റ്",
      marketing: "മാർക്കറ്റിംഗ്",
      faq: "പതിവുചോദ്യങ്ങൾ",
    },
    signOut: {
      button: "സൈൻ ഔട്ട് ചെയ്യുക",
      title: "സൈൻ ഔട്ട് ചെയ്തു",
      description: "നിങ്ങൾ വിജയകരമായി സൈൻ ഔട്ട് ചെയ്തു.",
      errorTitle: "സൈൻ ഔട്ട് പരാജയപ്പെട്ടു"
    },
    auth: {
      welcome: "മൻവാസത്തിലേക്ക് സ്വാഗതം",
      getStarted: "ആരംഭിക്കാൻ സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ ഒരു അക്കൗണ്ട് ഉണ്ടാക്കുക.",
      login: "പ്രവേശിക്കുക",
      register: "രജിസ്റ്റർ ചെയ്യുക",
      emailPassword: "ഇമെയിൽ & പാസ്‌വേഡ്",
      farmerFaceSignIn: "കർഷക മുഖം സൈൻ-ഇൻ",
      emailLabel: "ഇമെയിൽ",
      passwordLabel: "പാസ്വേഡ്",
      forgotPassword: "പാസ്വേഡ് മറന്നോ?",
      forgotPasswordTitle: "പാസ്വേഡ് മറന്നോ",
      forgotPasswordDesc: "നിങ്ങളുടെ ഇമെയിൽ നൽകുക, ഞങ്ങൾ ഒരു പുനഃസജ്ജീകരണ ലിങ്ക് അയയ്ക്കും.",
      sendResetLink: "പുനഃസജ്ജീകരണ ലിങ്ക് അയയ്ക്കുക",
      cancel: "റദ്ദാക്കുക",
      signIn: "സൈൻ ഇൻ ചെയ്യുക",
      iamA: "ഞാൻ ഒരു...",
      customer: "ഉപഭോക്താവ്",
      farmer: "കർഷകൻ",
      faceReg: "മുഖം രജിസ്ട്രേഷൻ",
      faceRegDesc: "നിങ്ങളുടെ മുഖം ക്യാമറയിൽ കേന്ദ്രീകരിച്ച് ക്യാപ്ചർ ക്ലിക്കുചെയ്യുക.",
      capturePhoto: "ഫോട്ടോ എടുക്കുക",
      photoCaptured: "ഫോട്ടോ വിജയകരമായി എടുത്തു!",
      retakePhoto: "വീണ്ടും ഫോട്ടോ എടുക്കുക",
      usernameLabel: "ഉപയോക്തൃനാമം",
      phoneLabel: "ഫോൺ നമ്പർ",
      confirmPasswordLabel: "പാസ്വേഡ് സ്ഥിരീകരിക്കുക",
      createAccount: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
      hubPortal: "ഹബ് പോർട്ടൽ",
      hubDesc: "ലോജിസ്റ്റിക്സ് നിയന്ത്രിക്കുകയും ഞങ്ങളുടെ നെറ്റ്‌വർക്കിനെ ബന്ധിപ്പിക്കുകയും ചെയ്യുക.",
      branchNameLabel: "ബ്രാഞ്ചിന്റെ പേര്",
      branchIdLabel: "ബ്രാഞ്ച് ഐഡി",
      hubAdminEmailLabel: "ഹബ് അഡ്മിൻ ഇമെയിൽ",
      registerHub: "ഹബ് രജിസ്റ്റർ ചെയ്യുക",
      restaurantPortal: "റെസ്റ്റോറന്റ് പോർട്ടൽ",
      restaurantDesc: "നിങ്ങളുടെ അക്കൗണ്ട് ആക്‌സസ് ചെയ്യുക അല്ലെങ്കിൽ നിങ്ങളുടെ റെസ്റ്റോറന്റ് രജിസ്റ്റർ ചെയ്യുക.",
      restaurantIdLabel: "റെസ്റ്റോറന്റ് ഐഡി",
      restaurantIdPlaceholder: "നിങ്ങളുടെ തനതായ റെസ്റ്റോറന്റ് ഐഡി",
      forgotPasswordRestaurantDesc: "പാസ്‌വേഡ് പുനഃസജ്ജീകരണ ലിങ്ക് ലഭിക്കുന്നതിന് നിങ്ങളുടെ റെസ്റ്റോറന്റ് ഐഡിയോ ഇമെയിലോ നൽകുക.",
      restaurantIdOrEmailLabel: "റെസ്റ്റോറന്റ് ഐഡി അല്ലെങ്കിൽ ഇമെയിൽ",
      restaurantIdOrEmailPlaceholder: "ഐഡി അല്ലെങ്കിൽ ഇമെയിൽ",
      restaurantNameLabel: "റെസ്റ്റോറന്റിന്റെ പേര്",
      restaurantEmailLabel: "റെസ്റ്റോറന്റ് ഇമെയിൽ",
      restaurantPhoneLabel: "റെസ്റ്റോറന്റ് ഫോൺ",
      locationLabel: "സ്ഥലം",
      registerRestaurant: "റെസ്റ്റോറന്റ് രജിസ്റ്റർ ചെയ്യുക",
    }
  },
  Telugu: {
    tagline: "రైతులకు సాధికారత, తాజాదనాన్ని అందించడం",
    joinCommunity: "మా సంఘంలో చేరండి",
    roles: {
      farmer: {
        name: "రైతు",
        description: "మీ ఉత్పత్తులను నేరుగా విక్రయించడానికి మా నెట్వర్క్‌లో చేరండి.",
      },
      customer: {
        name: "వినియోగదారుడు",
        description: "తాజా, సేంద్రీయ ఉత్పత్తులను మీ ఇంటి వద్ద పొందండి.",
      },
      hub: {
        name: "హబ్",
        description: "లాజిస్టిక్స్ నిర్వహించండి మరియు రైతులను వినియోగదారులతో కనెక్ట్ చేయండి.",
      },
       restaurant: {
        name: "రెస్టారెంట్",
        description: "స్థానిక పొలాల నుండి నేరుగా తాజా పదార్థాలను పొందండి.",
      },
    },
    continue: "కొనసాగించు",
    ourMission: "మా లక్ష్యం",
    missionStatement: "సుస్థిర వ్యవసాయానికి మద్దతు ఇస్తూ, తాజా సేంద్రీయ ఉత్పత్తులను మీరు పొందేలా మా విశ్వసనీయ హబ్ నెట్‌వర్క్ ద్వారా మన్వాసం మిమ్మల్ని స్థానిక రైతులతో నేరుగా కలుపుతుంది.",
    footer: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
    sidebar: {
      dashboard: "డాష్బోర్డ్",
      profile: "ప్రొఫైల్",
      orders: "ఆదేశాలు",
      products: "ఉత్పత్తులు",
      track: "ఆర్డర్ ట్రాక్ చేయండి",
      matchmaking: "మ్యాచ్ మేకింగ్",
      voiceAssistant: "వాయిస్ అసిస్టెంట్",
      marketing: "మార్కెటింగ్",
      faq: "ఎఫ్ ఎ క్యూ",
    },
     signOut: {
      button: "సైన్ అవుట్ చేయండి",
      title: "సైన్ అవుట్ చేయబడింది",
      description: "మీరు విజయవంతంగా సైన్ అవుట్ చేసారు.",
      errorTitle: "సైన్ అవుట్ విఫలమైంది"
    },
    auth: {
      welcome: "మన్వాసంకు స్వాగతం",
      getStarted: "ప్రారంభించడానికి సైన్ ఇన్ చేయండి లేదా ఖాతాను సృష్టించండి.",
      login: "లాగిన్",
      register: "నమోదు చేసుకోండి",
      emailPassword: "ఇమెయిల్ & పాస్వర్డ్",
      farmerFaceSignIn: "రైతు ఫేస్ సైన్-ఇన్",
      emailLabel: "ఇమెయిల్",
      passwordLabel: "పాస్వర్డ్",
      forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
      forgotPasswordTitle: "పాస్వర్డ్ మర్చిపోయారా",
      forgotPasswordDesc: "మీ ఇమెయిల్‌ను నమోదు చేయండి మరియు మేము రీసెట్ లింక్‌ను పంపుతాము.",
      sendResetLink: "రీసెట్ లింక్‌ను పంపండి",
      cancel: "రద్దు చేయండి",
      signIn: "సైన్ ఇన్ చేయండి",
      iamA: "నేను ఒక...",
      customer: "వినియోగదారుడు",
      farmer: "రైతు",
      faceReg: "ఫేస్ రిజిస్ట్రేషన్",
      faceRegDesc: "మీ ముఖాన్ని కెమెరాలో కేంద్రీకరించండి మరియు క్యాప్చర్ క్లిక్ చేయండి.",
      capturePhoto: "ఫోటోను క్యాప్చర్ చేయండి",
      photoCaptured: "ఫోటో విజయవంతంగా క్యాప్చర్ చేయబడింది!",
      retakePhoto: "ఫోటోను మళ్లీ తీసుకోండి",
      usernameLabel: "యూజర్పేరు",
      phoneLabel: "ఫోను నంబరు",
      confirmPasswordLabel: "పాస్వర్డ్ను నిర్ధారించండి",
      createAccount: "ఖాతాను సృష్టించండి",
      hubPortal: "హబ్ పోర్టల్",
      hubDesc: "లాజిస్టిక్స్ నిర్వహించండి మరియు మా నెట్‌వర్క్‌ను కనెక్ట్ చేయండి.",
      branchNameLabel: "శాఖ పేరు",
      branchIdLabel: "శాఖ ఐడి",
      hubAdminEmailLabel: "హబ్ అడ్మిన్ ఇమెయిల్",
      registerHub: "హబ్‌ను నమోదు చేయండి",
      restaurantPortal: "రెస్టారెంట్ పోర్టల్",
      restaurantDesc: "మీ ఖాతాను యాక్సెస్ చేయండి లేదా మీ రెస్టారెంట్‌ను నమోదు చేయండి.",
      restaurantIdLabel: "రెస్టారెంట్ ఐడి",
      restaurantIdPlaceholder: "మీ ప్రత్యేక రెస్టారెంట్ ఐడి",
      forgotPasswordRestaurantDesc: "పాస్‌వర్డ్ రీసెట్ లింక్‌ను స్వీకరించడానికి మీ రెస్టారెంట్ ఐడి లేదా ఇమెయిల్‌ను నమోదు చేయండి.",
      restaurantIdOrEmailLabel: "రెస్టారెంట్ ఐడి లేదా ఇమెయిల్",
      restaurantIdOrEmailPlaceholder: "ఐడి లేదా ఇమెయిల్",
      restaurantNameLabel: "రెస్టారెంట్ పేరు",
      restaurantEmailLabel: "రెస్టారెంట్ ఇమెయిల్",
      restaurantPhoneLabel: "రెస్టారెంట్ ఫోన్",
      locationLabel: "స్థానం",
      registerRestaurant: "రెస్టారెంట్‌ను నమోదు చేయండి",
    }
  },
  Hindi: {
    tagline: "किसानों को सशक्त बनाना, ताजगी पहुंचाना",
    joinCommunity: "हमारे समुदाय में शामिल हों",
    roles: {
      farmer: {
        name: "किसान",
        description: "अपनी उपज सीधे बेचने के लिए हमारे नेटवर्क से जुड़ें।",
      },
      customer: {
        name: "ग्राहक",
        description: "ताजा, जैविक उत्पाद अपने दरवाजे पर प्राप्त करें।",
      },
      hub: {
        name: "हब",
        description: "लॉजिस्टिक्स प्रबंधित करें और किसानों को ग्राहकों से जोड़ें।",
      },
       restaurant: {
        name: "रेस्टोरेंट",
        description: "स्थानीय खेतों से सीधे ताजा सामग्री प्राप्त करें।",
      },
    },
    continue: "जारी रखें",
    ourMission: "हमारा विशेष कार्य",
    missionStatement: "मनवासम आपको हमारे विश्वसनीय हब नेटवर्क के माध्यम से सीधे स्थानीय किसानों से जोड़ता है, यह सुनिश्चित करता है कि आपको स्थायी कृषि का समर्थन करते हुए सबसे ताज़ा जैविक उत्पाद प्राप्त हों।",
    footer: "सर्वाधिकार सुरक्षित।",
     sidebar: {
      dashboard: "डैशबोर्ड",
      profile: "प्रोफ़ाइल",
      orders: "आदेश",
      products: "उत्पादों",
      track: "ऑर्डर ट्रैक करें",
      matchmaking: "मैचमेकिंग",
      voiceAssistant: "आवाज सहायक",
      marketing: "विपणन",
      faq: "सामान्य प्रश्न",
    },
     signOut: {
      button: "साइन आउट",
      title: "साइन आउट किया गया",
      description: "आप सफलतापूर्वक साइन आउट हो गए हैं।",
      errorTitle: "साइन आउट विफल"
    },
    auth: {
      welcome: "मनवासम में आपका स्वागत है",
      getStarted: "शुरू करने के लिए साइन इन करें या एक खाता बनाएँ।",
      login: "लॉग इन करें",
      register: "पंजीकरण करवाना",
      emailPassword: "ईमेल और पासवर्ड",
      farmerFaceSignIn: "किसान फेस साइन-इन",
      emailLabel: "ईमेल",
      passwordLabel: "पासवर्ड",
      forgotPassword: "पासवर्ड भूल गए?",
      forgotPasswordTitle: "पासवर्ड भूल गए",
      forgotPasswordDesc: "अपना ईमेल दर्ज करें और हम एक रीसेट लिंक भेजेंगे।",
      sendResetLink: "रीसेट लिंक भेजें",
      cancel: "रद्द करें",
      signIn: "साइन इन करें",
      iamA: "मैं एक...",
      customer: "ग्राहक",
      farmer: "किसान",
      faceReg: "फेस पंजीकरण",
      faceRegDesc: "अपने चेहरे को कैमरे में केंद्रित करें और कैप्चर पर क्लिक करें।",
      capturePhoto: "फोटो कैप्चर करें",
      photoCaptured: "फोटो सफलतापूर्वक कैप्चर किया गया!",
      retakePhoto: "फोटो फिर से लें",
      usernameLabel: "उपयोगकर्ता नाम",
      phoneLabel: "फोन नंबर",
      confirmPasswordLabel: "पासवर्ड की पुष्टि कीजिये",
      createAccount: "खाता बनाएं",
      hubPortal: "हब पोर्टल",
      hubDesc: "लॉजिस्टिक्स प्रबंधित करें और हमारे नेटवर्क को कनेक्ट करें।",
      branchNameLabel: "शाखा का नाम",
      branchIdLabel: "शाखा आईडी",
      hubAdminEmailLabel: "हब व्यवस्थापक ईमेल",
      registerHub: "हब पंजीकृत करें",
      restaurantPortal: "रेस्तरां पोर्टल",
      restaurantDesc: "अपने खाते तक पहुंचें या अपने रेस्तरां को पंजीकृत करें।",
      restaurantIdLabel: "रेस्तरां आईडी",
      restaurantIdPlaceholder: "आपकी अनूठी रेस्तरां आईडी",
      forgotPasswordRestaurantDesc: "पासवर्ड रीसेट लिंक प्राप्त करने के लिए अपनी रेस्तरां आईडी या ईमेल दर्ज करें।",
      restaurantIdOrEmailLabel: "रेस्तरां आईडी या ईमेल",
      restaurantIdOrEmailPlaceholder: "आईडी या ईमेल",
      restaurantNameLabel: "रेस्तरां का नाम",
      restaurantEmailLabel: "रेस्तरां ईमेल",
      restaurantPhoneLabel: "रेस्तरां फोन",
      locationLabel: "स्थान",
      registerRestaurant: "रेस्तरां पंजीकृत करें",
    }
  },
  Kannada: {
    tagline: "ರೈತರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು, ತಾಜಾತನವನ್ನು ತಲುಪಿಸುವುದು",
    joinCommunity: "ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ",
    roles: {
      farmer: {
        name: "ರೈತ",
        description: "ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳನ್ನು ನೇರವಾಗಿ ಮಾರಾಟ ಮಾಡಲು ನಮ್ಮ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ.",
      },
      customer: {
        name: "ಗ್ರಾಹಕ",
        description: "ತಾಜಾ, ಸಾವಯವ ಉತ್ಪನ್ನಗಳನ್ನು ನಿಮ್ಮ ಮನೆ ಬಾಗಿಲಿಗೆ ತಲುಪಿಸಲಾಗುತ್ತದೆ.",
      },
      hub: {
        name: "ಕೇಂದ್ರ",
        description: "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಅನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ರೈತರನ್ನು ಗ್ರಾಹಕರಿಗೆ ಸಂಪರ್ಕಿಸಿ.",
      },
       restaurant: {
        name: "ರೆಸ್ಟೋರೆಂಟ್",
        description: "ಸ್ಥಳೀಯ ಜಮೀನುಗಳಿಂದ ನೇರವಾಗಿ ತಾಜಾ ಪದಾರ್ಥಗಳನ್ನು ಪಡೆಯಿರಿ.",
      },
    },
    continue: "ಮುಂದುವರಿಸಿ",
    ourMission: "ನಮ್ಮ ಧ್ಯೇಯ",
    missionStatement: "ಮನ್ವಾಸಂ ನಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಕೇಂದ್ರ ನೆಟ್‌ವರ್ಕ್ ಮೂಲಕ ನಿಮ್ಮನ್ನು ಸ್ಥಳೀಯ ರೈತರೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ, ಸುಸ್ಥಿರ ಕೃಷಿಯನ್ನು ಬೆಂಬಲಿಸುವಾಗ ನೀವು ತಾಜಾ ಸಾವಯವ ಉತ್ಪನ್ನಗಳನ್ನು ಪಡೆಯುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
    footer: "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    sidebar: {
      dashboard: "ಡ್ಯಾಶ್ಬೋರ್ಡ್",
      profile: "ಪ್ರೊಫೈಲ್",
      orders: "ಆದೇಶಗಳು",
      products: "ಉತ್ಪನ್ನಗಳು",
      track: "ಆದೇಶವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
      matchmaking: "ಮ್ಯಾಚ್ ಮೇಕಿಂಗ್",
      voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ",
      marketing: "ಮಾರ್ಕೆಟಿಂಗ್",
      faq: "ఎఫ్ఎక్యూ",
    },
    signOut: {
      button: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
      title: "ಸೈನ್ ಔಟ್ ಮಾಡಲಾಗಿದೆ",
      description: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಿದ್ದೀರಿ.",
      errorTitle: "ಸೈನ್ ಔಟ್ ವಿಫಲವಾಗಿದೆ"
    },
    auth: {
      welcome: "ಮನ್ವಾಸಂಗೆ ಸ್ವಾಗತ",
      getStarted: "ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ಖಾತೆಯನ್ನು ರಚಿಸಿ.",
      login: "ಲಾಗಿನ್ ಮಾಡಿ",
      register: "ನೋಂದಣಿ ಮಾಡಿ",
      emailPassword: "ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್ವರ್ಡ್",
      farmerFaceSignIn: "ರೈತ ಮುಖ ಸೈನ್-ಇನ್",
      emailLabel: "ಇಮೇಲ್",
      passwordLabel: "ಪಾಸ್ವರ್ಡ್",
      forgotPassword: "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?",
      forgotPasswordTitle: "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ",
      forgotPasswordDesc: "ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ನಾವು ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಅನ್ನು ಕಳುಹಿಸುತ್ತೇವೆ.",
      sendResetLink: "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
      cancel: "ರದ್ದುಮಾಡಿ",
      signIn: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
      iamA: "ನಾನು ಒಬ್ಬ...",
      customer: "ಗ್ರಾಹಕ",
      farmer: "ರೈತ",
      faceReg: "ಮುಖ ನೋಂದಣಿ",
      faceRegDesc: "ನಿಮ್ಮ ಮುಖವನ್ನು ಕ್ಯಾಮರಾದಲ್ಲಿ ಕೇಂದ್ರೀಕರಿಸಿ ಮತ್ತು ಕ್ಯಾಪ್ಚರ್ ಕ್ಲಿಕ್ ಮಾಡಿ.",
      capturePhoto: "ಫೋಟೋ ಸೆರೆಹಿಡಿಯಿರಿ",
      photoCaptured: "ಫೋಟೋ ಯಶಸ್ವಿಯಾಗಿ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ!",
      retakePhoto: "ಫೋಟೋವನ್ನು ಮರುಪಡೆಯಿರಿ",
      usernameLabel: "ಬಳಕೆದಾರಹೆಸರು",
      phoneLabel: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
      confirmPasswordLabel: "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
      createAccount: "ಖಾತೆ ತೆರೆ",
      hubPortal: "ಹಬ್ ಪೋರ್ಟಲ್",
      hubDesc: "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಅನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ನಮ್ಮ ನೆಟ್ವರ್ಕ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.",
      branchNameLabel: "ಶಾಖೆಯ ಹೆಸರು",
      branchIdLabel: "ಶಾಖೆ ಐಡಿ",
      hubAdminEmailLabel: "ಹಬ್ ನಿರ್ವಾಹಕ ಇಮೇಲ್",
      registerHub: "ಹಬ್ ನೋಂದಾಯಿಸಿ",
      restaurantPortal: "ರೆಸ್ಟೋರೆಂಟ್ ಪೋರ್ಟಲ್",
      restaurantDesc: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪ್ರವೇಶಿಸಿ ಅಥವಾ ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಅನ್ನು ನೋಂದಾಯಿಸಿ.",
      restaurantIdLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ",
      restaurantIdPlaceholder: "ನಿಮ್ಮ ಅನನ್ಯ ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ",
      forgotPasswordRestaurantDesc: "ಪಾಸ್ವರ್ಡ್ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಅನ್ನು ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ ಅಥವಾ ಇಮೇಲ್ ಅನ್ನು ನಮೂದಿಸಿ.",
      restaurantIdOrEmailLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಐಡಿ ಅಥವಾ ಇಮೇಲ್",
      restaurantIdOrEmailPlaceholder: "ಐಡಿ ಅಥವಾ ಇಮೇಲ್",
      restaurantNameLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಹೆಸರು",
      restaurantEmailLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಇಮೇಲ್",
      restaurantPhoneLabel: "ರೆಸ್ಟೋರೆಂಟ್ ಫೋನ್",
      locationLabel: "ಸ್ಥಳ",
      registerRestaurant: "ರೆಸ್ಟೋರೆಂಟ್ ನೋಂದಾಯಿಸಿ",
    }
  },
  Bengali: {
    tagline: "কৃষকদের ক্ষমতায়ন, সতেজতা সরবরাহ",
    joinCommunity: "আমাদের সম্প্রদায়ে যোগ দিন",
    roles: {
      farmer: {
        name: "কৃষক",
        description: "আপনার পণ্য সরাসরি বিক্রি করতে আমাদের নেটওয়ার্কে যোগ দিন।",
      },
      customer: {
        name: "গ্রাহক",
        description: "তাজা, জৈব পণ্য আপনার দোরগোড়ায় পৌঁছে দেওয়া হয়।",
      },
      hub: {
        name: "হাব",
        description: "লজিস্টিক পরিচালনা করুন এবং কৃষকদের গ্রাহকদের সাথে সংযুক্ত করুন।",
      },
       restaurant: {
        name: "রেস্তোরাঁ",
        description: "স্থানীয় খামার থেকে সরাসরি তাজা উপাদান সংগ্রহ করুন।",
      },
    },
    continue: "চালিয়ে যান",
    ourMission: "আমাদের লক্ষ্য",
    missionStatement: "মনওয়াসম আমাদের বিশ্বস্ত হাব নেটওয়ার্কের মাধ্যমে আপনাকে স্থানীয় কৃষকদের সাথে সরাসরি সংযুক্ত করে, টেকসই কৃষিকে সমর্থন করার সময় আপনি তাজা জৈব পণ্য পান তা নিশ্চিত করে।",
    footer: "সমস্ত অধিকার সংরক্ষিত।",
    sidebar: {
      dashboard: "ড্যাশবোর্ড",
      profile: "প্রোফাইল",
      orders: "অর্ডার",
      products: "পণ্য",
      track: "অর্ডার ট্র্যাক করুন",
      matchmaking: "ম্যাচমেকিং",
      voiceAssistant: "ভয়েস সহকারী",
      marketing: "বিপণন",
      faq: "FAQ",
    },
    signOut: {
      button: "সাইন আউট",
      title: "সাইন আউট করা হয়েছে",
      description: "আপনি সফলভাবে সাইন আউট হয়েছেন।",
      errorTitle: "সাইন আউট ব্যর্থ হয়েছে"
    },
    auth: {
      welcome: "মনওয়াসম-এ স্বাগতম",
      getStarted: "শুরু করতে সাইন ইন করুন বা একটি অ্যাকাউন্ট তৈরি করুন।",
      login: "লগইন",
      register: "নিবন্ধন করুন",
      emailPassword: "ইমেল এবং পাসওয়ার্ড",
      farmerFaceSignIn: "কৃষক ফেস সাইন-ইন",
      emailLabel: "ইমেল",
      passwordLabel: "পাসওয়ার্ড",
      forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
      forgotPasswordTitle: "পাসওয়ার্ড ভুলে গেছেন",
      forgotPasswordDesc: "আপনার ইমেল লিখুন এবং আমরা একটি রিসেট লিঙ্ক পাঠাব।",
      sendResetLink: "রিসেট লিঙ্ক পাঠান",
      cancel: "বাতিল করুন",
      signIn: "সাইন ইন করুন",
      iamA: "আমি একজন...",
      customer: "গ্রাহক",
      farmer: "কৃষক",
      faceReg: "ফেস রেজিস্ট্রেশন",
      faceRegDesc: "আপনার মুখ ক্যামেরায় কেন্দ্র করুন এবং ক্যাপচারে ক্লিক করুন।",
      capturePhoto: "ছবি ক্যাপচার করুন",
      photoCaptured: "ছবি সফলভাবে ক্যাপচার করা হয়েছে!",
      retakePhoto: "ছবি আবার তুলুন",
      usernameLabel: "ব্যবহারকারীর নাম",
      phoneLabel: "ফোন নম্বর",
      confirmPasswordLabel: "পাসওয়ার্ড নিশ্চিত করুন",
      createAccount: "অ্যাকাউন্ট তৈরি করুন",
      hubPortal: "হাব পোর্টাল",
      hubDesc: "লজিস্টিক পরিচালনা করুন এবং আমাদের নেটওয়ার্ক সংযোগ করুন।",
      branchNameLabel: "শাখার নাম",
      branchIdLabel: "শাখা আইডি",
      hubAdminEmailLabel: "হাব অ্যাডমিন ইমেল",
      registerHub: "হাব নিবন্ধন করুন",
      restaurantPortal: "রেস্তোরাঁ পোর্টাল",
      restaurantDesc: "আপনার অ্যাকাউন্ট অ্যাক্সেস করুন বা আপনার রেস্তোরাঁ নিবন্ধন করুন।",
      restaurantIdLabel: "রেস্তোরাঁ আইডি",
      restaurantIdPlaceholder: "আপনার অনন্য রেস্তোরাঁ আইডি",
      forgotPasswordRestaurantDesc: "পাসওয়ার্ড রিসেট লিঙ্ক পেতে আপনার রেস্তোরাঁ আইডি বা ইমেল লিখুন।",
      restaurantIdOrEmailLabel: "রেস্তোরাঁ আইডি বা ইমেল",
      restaurantIdOrEmailPlaceholder: "আইডি বা ইমেল",
      restaurantNameLabel: "রেস্তোরাঁর নাম",
      restaurantEmailLabel: "রেস্তোরাঁর ইমেল",
      restaurantPhoneLabel: "রেস্তোরাঁর ফোন",
      locationLabel: "অবস্থান",
      registerRestaurant: "রেস্তোরাঁ নিবন্ধন করুন",
    }
  },
  Arabic: {
    tagline: "تمكين المزارعين، وتوصيل المنتجات الطازجة",
    joinCommunity: "انضم إلى مجتمعنا",
    roles: {
      farmer: {
        name: "مزارع",
        description: "انضم إلى شبكتنا لبيع منتجاتك مباشرة.",
      },
      customer: {
        name: "عميل",
        description: "احصل على منتجات عضوية طازجة تصل إلى عتبة داركم.",
      },
      hub: {
        name: "مركز",
        description: "إدارة الخدمات اللوجستية وربط المزارعين بالعملاء.",
      },
      restaurant: {
        name: "مطعم",
        description: "احصل على المكونات الطازجة مباشرة من المزارع المحلية.",
      },
    },
    continue: "متابعة",
    ourMission: "مهمتنا",
    missionStatement: "تقوم مانواسام بتوصيلك مباشرة بالمزارعين المحليين من خلال شبكة مراكزنا الموثوقة، مما يضمن حصولك على المنتجات العضوية الطازجة مع دعم الزراعة المستدامة.",
    footer: "كل الحقوق محفوظة.",
    sidebar: {
        dashboard: "لوحة القيادة",
        profile: "الملف الشخصي",
        orders: "الطلبات",
        products: "المنتجات",
        track: "تتبع الطلب",
        matchmaking: "التوفيق",
        voiceAssistant: "مساعد صوتي",
        marketing: "التسويق",
        faq: "التعليمات",
    },
    signOut: {
        button: "تسجيل الخروج",
        title: "تم تسجيل الخروج",
        description: "لقد تم تسجيل خروجك بنجاح.",
        errorTitle: "فشل تسجيل الخروج"
    },
    auth: {
      welcome: "مرحبًا بك في مانواسام",
      getStarted: "للبدء، قم بتسجيل الدخول أو إنشاء حساب.",
      login: "تسجيل الدخول",
      register: "تسجيل",
      emailPassword: "البريد الإلكتروني وكلمة المرور",
      farmerFaceSignIn: "تسجيل دخول المزارع بالوجه",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      forgotPasswordTitle: "هل نسيت كلمة المرور",
      forgotPasswordDesc: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.",
      sendResetLink: "إرسال رابط إعادة التعيين",
      cancel: "إلغاء",
      signIn: "تسجيل الدخول",
      iamA: "أنا...",
      customer: "عميل",
      farmer: "مزارع",
      faceReg: "تسجيل الوجه",
      faceRegDesc: "ضع وجهك في وسط الكاميرا وانقر على التقاط.",
      capturePhoto: "التقاط صورة",
      photoCaptured: "تم التقاط الصورة بنجاح!",
      retakePhoto: "إعادة التقاط الصورة",
      usernameLabel: "اسم المستخدم",
      phoneLabel: "رقم الهاتف",
      confirmPasswordLabel: "تأكيد كلمة المرور",
      createAccount: "إنشاء حساب",
      hubPortal: "بوابة المركز",
      hubDesc: "إدارة الخدمات اللوجستية وربط شبكتنا.",
      branchNameLabel: "اسم الفرع",
      branchIdLabel: "معرف الفرع",
      hubAdminEmailLabel: "البريد الإلكتروني لمسؤول المركز",
      registerHub: "تسجيل المركز",
      restaurantPortal: "بوابة المطعم",
      restaurantDesc: "الوصول إلى حسابك أو تسجيل مطعمك.",
      restaurantIdLabel: "معرف المطعم",
      restaurantIdPlaceholder: "معرف المطعم الفريد الخاص بك",
      forgotPasswordRestaurantDesc: "أدخل معرف المطعم أو البريد الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.",
      restaurantIdOrEmailLabel: "معرف المطعم أو البريد الإلكتروني",
      restaurantIdOrEmailPlaceholder: "المعرف أو البريد الإلكتروني",
      restaurantNameLabel: "اسم المطعم",
      restaurantEmailLabel: "البريد الإلكتروني للمطعم",
      restaurantPhoneLabel: "هاتف المطعم",
      locationLabel: "الموقع",
      registerRestaurant: "تسجيل مطعم",
    }
  },
  Urdu: {
    tagline: "کسانوں کو بااختیار بنانا، تازگی فراہم کرنا",
    joinCommunity: "ہماری کمیونٹی میں شامل ہوں",
    roles: {
      farmer: {
        name: "کسان",
        description: "اپنی پیداوار براہ راست فروخت کرنے کے لیے ہمارے نیٹ ورک میں شامل ہوں۔",
      },
      customer: {
        name: "گاہک",
        description: "تازہ، نامیاتی مصنوعات اپنی دہلیز پر حاصل کریں۔",
      },
      hub: {
        name: "مرکز",
        description: "لاجسٹکس کا نظم کریں اور کسانوں کو صارفین سے جوڑیں۔",
      },
      restaurant: {
        name: "ریستوراں",
        description: "مقامی فارموں سے براہ راست تازہ اجزاء حاصل کریں۔",
      },
    },
    continue: "جاری رکھیں",
    ourMission: "ہمارا مقصد",
    missionStatement: "منواسام آپ کو ہمارے قابل اعتماد مرکز نیٹ ورک کے ذریعے براہ راست مقامی کسانوں سے جوڑتا ہے، اس بات کو یقینی بناتا ہے کہ آپ پائیدار زراعت کی حمایت کرتے ہوئے تازہ ترین نامیاتی مصنوعات حاصل کریں۔",
    footer: "جملہ حقوق محفوظ ہیں۔",
    sidebar: {
        dashboard: "ڈیش بورڈ",
        profile: "پروفائل",
        orders: "آرڈرز",
        products: "مصنوعات",
        track: "آرڈر ٹریک کریں",
        matchmaking: " میچ میکنگ",
        voiceAssistant: "وائس اسسٹنٹ",
        marketing: "مارکیٹنگ",
        faq: "اکثر पूछे گئے سوالات",
    },
    signOut: {
        button: "সাইন আউট",
        title: "সাইন আউট করা হয়েছে",
        description: "আপনি সফলভাবে সাইন আউট হয়েছেন।",
        errorTitle: "সাইন আউট ব্যর্থ হয়েছে"
    },
    auth: {
      welcome: "منواسام میں خوش آمدید",
      getStarted: "شروع کرنے کے لیے سائن ان کریں یا ایک اکاؤنٹ بنائیں۔",
      login: "لاگ ان کریں",
      register: "رجسٹر کریں",
      emailPassword: "ای میل اور پاس ورڈ",
      farmerFaceSignIn: "کسان فیس سائن ان",
      emailLabel: "ای میل",
      passwordLabel: "پاس ورڈ",
      forgotPassword: "پاس ورڈ بھول گئے؟",
      forgotPasswordTitle: "پاس ورڈ بھول گئے",
      forgotPasswordDesc: "اپنا ای میل درج کریں اور ہم ایک ری سیٹ لنک بھیجیں گے۔",
      sendResetLink: "ری سیٹ لنک بھیجیں",
      cancel: "منسوخ کریں",
      signIn: "سائن ان کریں",
      iamA: "میں ایک...",
      customer: "گاہک",
      farmer: "کسان",
      faceReg: "چہرے کی رجسٹریشن",
      faceRegDesc: "اپنے چہرے کو کیمرے میں مرکز کریں اور کیپچر پر کلک کریں۔",
      capturePhoto: "تصویر کیپچر کریں",
      photoCaptured: "تصویر کامیابی سے کیپچر ہوگئی!",
      retakePhoto: "دوبارہ تصویر لیں",
      usernameLabel: "صارف نام",
      phoneLabel: "فون نمبر",
      confirmPasswordLabel: "پاس ورڈ کی تصدیق کریں",
      createAccount: "اکاؤنٹ بنائیں",
      hubPortal: "حب پورٹل",
      hubDesc: "لاجسٹکس کا نظم کریں اور ہمارے نیٹ ورک کو جوڑیں۔",
      branchNameLabel: "برانچ کا نام",
      branchIdLabel: "برانچ آئی ڈی",
      hubAdminEmailLabel: "حب ایڈمن ای میل",
      registerHub: "حب رجسٹر کریں",
      restaurantPortal: "ریستوراں پورٹل",
      restaurantDesc: "اپنے اکاؤنٹ تک رسائی حاصل کریں یا اپنے ریستوراں کو رجسٹر کریں۔",
      restaurantIdLabel: "ریستوراں آئی ڈی",
      restaurantIdPlaceholder: "آپ کی منفرد ریستوراں آئی ڈی",
      forgotPasswordRestaurantDesc: "پاس ورڈ ری سیٹ لنک حاصل کرنے کے لیے اپنی ریستوراں آئی ڈی یا ای میل درج کریں۔",
      restaurantIdOrEmailLabel: "ریستوراں آئی ڈی یا ای میل",
      restaurantIdOrEmailPlaceholder: "آئی ڈی یا ای میل",
      restaurantNameLabel: "ریستوراں کا نام",
      restaurantEmailLabel: "ریستوراں ای میل",
      restaurantPhoneLabel: "ریستوراں فون",
      locationLabel: "مقام",
      registerRestaurant: "ریستوراں رجسٹر کریں",
    }
  },
  Srilanka: {
    tagline: "ගොවීන් සවිබල ගැන්වීම, නැවුම් බව ලබා දීම",
    joinCommunity: "අපගේ ප්‍රජාවට සම්බන්ධ වන්න",
    roles: {
      farmer: {
        name: "ගොවියා",
        description: "ඔබේ නිෂ්පාදන සෘජුවම විකිණීම සඳහා අපගේ ජාලයට සම්බන්ධ වන්න.",
      },
      customer: {
        name: "පාරිභෝගික",
        description: "නැවුම්, කාබනික නිෂ්පාදන ඔබේ දොරකඩටම ගෙන්වා ගන්න.",
      },
      hub: {
        name: "කේන්ද්‍රය",
        description: "ලොජිස්ටික්ස් කළමනාකරණය කර ගොවීන් පාරිಭෝගිකයන් හා සම්බන්ධ කරන්න.",
      },
      restaurant: {
        name: "ආපන ශාලාව",
        description: "දේශීය ගොවිපලවලින් නැවුම් අමුද්‍රව්‍ය සෘජුවම ලබා ගන්න.",
      },
    },
    continue: "ඉදිරියට යන්න",
    ourMission: "අපේ මෙහෙවර",
    missionStatement: "මන්වාசம் අපගේ විශ්වාසවන්ත මධ්‍යස්ථාන ජාලය හරහා ඔබව දේශීය ගොවීන් සමඟ සෘජුවම සම්බන්ධ කරයි, තිරසාර කෘෂිකර්මාන්තයට සහාය දෙන අතරම ඔබට නැවුම්ම කාබනික නිෂ්පාදන ලැබෙන බව සහතික කරයි.",
    footer: "සියලුම හිමිකම් ඇවිරිණි.",
    sidebar: {
        dashboard: "แดชบอร์ด",
        profile: "පැතිකඩ",
        orders: "ใบสั่งซื้อ",
        products: "නිෂ්පාදන",
        track: " ট্র্যাক অর্ডার",
        matchmaking: "ගැලපීම",
        voiceAssistant: "හඬ සහායක",
        marketing: "අලෙවිකරණය",
        faq: "නිතර අසන පැන",
    },
     signOut: {
        button: "ออกจากระบบ",
        title: "ออกจากระบบแล้ว",
        description: "คุณออกจากระบบเรียบร้อยแล้ว",
        errorTitle: "การออกจากระบบล้มเหลว"
    },
    auth: {
      welcome: "මන්වාසම් වෙත සාදරයෙන් පිළිගනිමු",
      getStarted: "ආරම්භ කිරීමට පුරනය වන්න හෝ ගිණුමක් සාදන්න.",
      login: "ඇතුල් වන්න",
      register: "ලියාපදිංචි වන්න",
      emailPassword: "විද්‍යුත් තැපෑල සහ මුරපදය",
      farmerFaceSignIn: "ගොවි මුහුණ පුරනය වීම",
      emailLabel: "විද්යුත් තැපෑල",
      passwordLabel: "මුරපදය",
      forgotPassword: "මුරපදය අමතක වුණා ද?",
      forgotPasswordTitle: "මුරපදය අමතක වුණා ද",
      forgotPasswordDesc: "ඔබගේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න, අපි යළි පිහිටුවීමේ සබැඳියක් එවන්නෙමු.",
      sendResetLink: "යළි පිහිටුවීමේ සබැඳිය යවන්න",
      cancel: "අუা करें",
      signIn: "පුරනය වන්න",
      iamA: "මම...",
      customer: "ಗ್ರಾಹಕ",
      farmer: "ගොවියා",
      faceReg: "මුහුණු ලියාපදිංචිය",
      faceRegDesc: "ඔබගේ මුහුණ කැමරාවේ මැදට ගෙන ග්‍රහණය ක්ලික් කරන්න.",
      capturePhoto: "ඡායාරූපය ගන්න",
      photoCaptured: "ඡායාරූපය සාර්ථකව ග්‍රහණය කර ඇත!",
      retakePhoto: "ඡායාරූපය නැවත ගන්න",
      usernameLabel: "පරිශීලක නාමය",
      phoneLabel: "දුරකථන අංකය",
      confirmPasswordLabel: "මුරපදය තහවුරු කරන්න",
      createAccount: "ගිණුම තනන්න",
      hubPortal: "හබ් ද්වාරය",
      hubDesc: "ලොජිස්ටික් කළමනාකරණය කර අපගේ ජාලය සම්බන්ධ කරන්න.",
      branchNameLabel: "ශාಖාවේ නම",
      branchIdLabel: "ශාඛා හැඳුනුම්පත",
      hubAdminEmailLabel: "හබ් පරිපාලක විද්‍යුත් තැපෑල",
      registerHub: "හබ් ලියාපදිංචි කරන්න",
      restaurantPortal: "ආපනශාලා ද්වාරය",
      restaurantDesc: "ඔබගේ ගිණුමට පිවිසෙන්න හෝ ඔබගේ ආපනශාලාව ලියාපදිංචි කරන්න.",
      restaurantIdLabel: "ආපනශාලා හැඳුනුම්පත",
      restaurantIdPlaceholder: "ඔබගේ අනන්‍ය ආපනශාලා හැඳුනුම්පත",
      forgotPasswordRestaurantDesc: "මුරපද යළි පිහිටුවීමේ සබැඳියක් ලබා ගැනීමට ඔබගේ ආපනශාලා හැඳුනුම්පත හෝ විද්‍යුත් තැපෑල ඇතුළත් කරන්න.",
      restaurantIdOrEmailLabel: "ආපනශාලා හැඳුනුම්පත හෝ විද්‍යුත් තැපෑල",
      restaurantIdOrEmailPlaceholder: "හැඳුනුම්පත හෝ විද්‍යුත් තැපෑල",
      restaurantNameLabel: "ආපනශාලාවේ නම",
      restaurantEmailLabel: "ආපනශාලා විද්‍යುත් තැපෑල",
      restaurantPhoneLabel: "ආපනශාලා දුරකථනය",
      locationLabel: "ස්ථානය",
      registerRestaurant: "ආපනශාලාව ලියාපදිංචි කරන්න",
    }
  },
};

export const languages = Object.keys(translations);

type Language = keyof typeof translations;

interface LanguageContextType {
  selectedLanguage: Language;
  setSelectedLanguage: (language: Language) => void;
  t: typeof translations[Language];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [selectedLanguage, setSelectedLanguage] = useState<Language>('English');

  useEffect(() => {
    const storedLanguage = localStorage.getItem('manvaasam-language') as Language;
    if (storedLanguage && translations[storedLanguage]) {
      setSelectedLanguage(storedLanguage);
    }
  }, []);

  const handleSetLanguage = (language: Language) => {
    setSelectedLanguage(language);
    if (typeof window !== 'undefined') {
      localStorage.setItem('manvaasam-language', language);
    }
  };
  
  const t = translations[selectedLanguage] || translations['English'];

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
